/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.FiltroDinamico;

import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author F20LAB303-XXE
 */
public class Mapa extends javax.swing.JPanel {

    private URL url=getClass().getResource("/FiltroDinamico/mapa.png");
    private Image imagen=new ImageIcon(url).getImage();
    private VentanaMapaProyectos pri;
    
    public Mapa(VentanaMapaProyectos pri) {
        initComponents();
        
        this.pri=pri;
        agruparRadioButton();
    }

    @Override
    public void paint(Graphics g) {
        if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
 
            setOpaque(false);
        } else {
            setOpaque(true);
        }
 
        super.paint(g);
    }
    
    public void agruparRadioButton(){
        ButtonGroup grupo1 = new ButtonGroup();
        grupo1.add(jRadioButtonLoreto);
        grupo1.add(jRadioButtonTumbes);
        grupo1.add(jRadioButtonPiura);
        grupo1.add(jRadioButtonAmazonas);
        grupo1.add(jRadioButtonLambayeque);
        grupo1.add(jRadioButtonCajamarca);
        grupo1.add(jRadioButtonSanMartin);
        grupo1.add(jRadioButtonLaLibertad);
        grupo1.add(jRadioButtonHuanuco);
        grupo1.add(jRadioButtonUcayali);
        grupo1.add(jRadioButtonAncash);
        grupo1.add(jRadioButtonPasco);
        grupo1.add(jRadioButtonJunin);
        grupo1.add(jRadioButtonLima);
        grupo1.add(jRadioButtonMadredeDios);
        grupo1.add(jRadioButtonHuancavelica);
        grupo1.add(jRadioButtonCusco);
        grupo1.add(jRadioButtonIca);
        grupo1.add(jRadioButtonApurimac);
        grupo1.add(jRadioButtonPuno);
        grupo1.add(jRadioButtonAyacucho);
        grupo1.add(jRadioButtonArequipa);
        grupo1.add(jRadioButtonMoquegua);
        grupo1.add(jRadioButtonTacna);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonLoreto = new javax.swing.JRadioButton();
        jRadioButtonTumbes = new javax.swing.JRadioButton();
        jRadioButtonPiura = new javax.swing.JRadioButton();
        jRadioButtonLambayeque = new javax.swing.JRadioButton();
        jRadioButtonAmazonas = new javax.swing.JRadioButton();
        jRadioButtonSanMartin = new javax.swing.JRadioButton();
        jRadioButtonCajamarca = new javax.swing.JRadioButton();
        jRadioButtonLaLibertad = new javax.swing.JRadioButton();
        jRadioButtonAncash = new javax.swing.JRadioButton();
        jRadioButtonHuanuco = new javax.swing.JRadioButton();
        jRadioButtonUcayali = new javax.swing.JRadioButton();
        jRadioButtonLima = new javax.swing.JRadioButton();
        jRadioButtonIca = new javax.swing.JRadioButton();
        jRadioButtonArequipa = new javax.swing.JRadioButton();
        jRadioButtonAyacucho = new javax.swing.JRadioButton();
        jRadioButtonTacna = new javax.swing.JRadioButton();
        jRadioButtonPuno = new javax.swing.JRadioButton();
        jRadioButtonMadredeDios = new javax.swing.JRadioButton();
        jRadioButtonCusco = new javax.swing.JRadioButton();
        jRadioButtonMoquegua = new javax.swing.JRadioButton();
        jRadioButtonApurimac = new javax.swing.JRadioButton();
        jRadioButtonHuancavelica = new javax.swing.JRadioButton();
        jRadioButtonPasco = new javax.swing.JRadioButton();
        jRadioButtonJunin = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButtonLoreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLoretoActionPerformed(evt);
            }
        });

        jRadioButtonTumbes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTumbesActionPerformed(evt);
            }
        });

        jRadioButtonPiura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPiuraActionPerformed(evt);
            }
        });

        jRadioButtonLambayeque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLambayequeActionPerformed(evt);
            }
        });

        jRadioButtonAmazonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAmazonasActionPerformed(evt);
            }
        });

        jRadioButtonSanMartin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSanMartinActionPerformed(evt);
            }
        });

        jRadioButtonCajamarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCajamarcaActionPerformed(evt);
            }
        });

        jRadioButtonLaLibertad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLaLibertadActionPerformed(evt);
            }
        });

        jRadioButtonAncash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAncashActionPerformed(evt);
            }
        });

        jRadioButtonHuanuco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHuanucoActionPerformed(evt);
            }
        });

        jRadioButtonUcayali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUcayaliActionPerformed(evt);
            }
        });

        jRadioButtonLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLimaActionPerformed(evt);
            }
        });

        jRadioButtonIca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIcaActionPerformed(evt);
            }
        });

        jRadioButtonArequipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonArequipaActionPerformed(evt);
            }
        });

        jRadioButtonAyacucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAyacuchoActionPerformed(evt);
            }
        });

        jRadioButtonTacna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTacnaActionPerformed(evt);
            }
        });

        jRadioButtonPuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPunoActionPerformed(evt);
            }
        });

        jRadioButtonMadredeDios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMadredeDiosActionPerformed(evt);
            }
        });

        jRadioButtonCusco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCuscoActionPerformed(evt);
            }
        });

        jRadioButtonMoquegua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMoqueguaActionPerformed(evt);
            }
        });

        jRadioButtonApurimac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonApurimacActionPerformed(evt);
            }
        });

        jRadioButtonHuancavelica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHuancavelicaActionPerformed(evt);
            }
        });

        jRadioButtonPasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPascoActionPerformed(evt);
            }
        });

        jRadioButtonJunin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonPiura)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jRadioButtonLambayeque)
                                .addGap(50, 50, 50)
                                .addComponent(jRadioButtonAmazonas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButtonLaLibertad)
                                    .addComponent(jRadioButtonCajamarca))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonLima)
                                    .addComponent(jRadioButtonSanMartin))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonJunin)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonTumbes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonLoreto))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jRadioButtonHuanuco)
                                .addGap(0, 71, Short.MAX_VALUE)))
                        .addGap(17, 17, 17)
                        .addComponent(jRadioButtonUcayali)
                        .addGap(179, 179, 179))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButtonTacna)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButtonMoquegua)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonAncash)
                                        .addGap(84, 84, 84)
                                        .addComponent(jRadioButtonPasco))
                                    .addComponent(jRadioButtonHuancavelica))
                                .addGap(73, 73, 73)
                                .addComponent(jRadioButtonCusco))
                            .addComponent(jRadioButtonArequipa))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButtonIca)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButtonAyacucho)
                        .addGap(118, 118, 118)
                        .addComponent(jRadioButtonMadredeDios)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButtonApurimac)
                        .addGap(88, 88, 88)
                        .addComponent(jRadioButtonPuno)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jRadioButtonLoreto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jRadioButtonTumbes)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jRadioButtonAmazonas)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSanMartin)
                                        .addGap(49, 49, 49)
                                        .addComponent(jRadioButtonUcayali))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jRadioButtonHuanuco)))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButtonAncash)
                                    .addComponent(jRadioButtonPasco))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonMadredeDios)
                                    .addComponent(jRadioButtonLima)
                                    .addComponent(jRadioButtonJunin)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jRadioButtonCajamarca)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButtonLaLibertad)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCusco)
                            .addComponent(jRadioButtonHuancavelica))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jRadioButtonPuno))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jRadioButtonIca))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jRadioButtonApurimac)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jRadioButtonArequipa)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonTacna, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButtonMoquegua)
                                        .addGap(43, 43, 43)))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jRadioButtonAyacucho)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jRadioButtonPiura)
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButtonLambayeque)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonLoretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLoretoActionPerformed
        try {
            pri.seleccionarDepartamento("Loreto","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonLoretoActionPerformed

    private void jRadioButtonTumbesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTumbesActionPerformed
        try {
            pri.seleccionarDepartamento("Tumbes","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonTumbesActionPerformed

    private void jRadioButtonPiuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPiuraActionPerformed
        try {
            pri.seleccionarDepartamento("Piura","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonPiuraActionPerformed

    private void jRadioButtonLambayequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLambayequeActionPerformed
        try {
            pri.seleccionarDepartamento("Lambayeque","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonLambayequeActionPerformed

    private void jRadioButtonAmazonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAmazonasActionPerformed
        try {
            pri.seleccionarDepartamento("Amazonas","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonAmazonasActionPerformed

    private void jRadioButtonSanMartinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSanMartinActionPerformed
        try {
            pri.seleccionarDepartamento("San Martín","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonSanMartinActionPerformed

    private void jRadioButtonCajamarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCajamarcaActionPerformed
        try {
            pri.seleccionarDepartamento("Cajamarca","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonCajamarcaActionPerformed

    private void jRadioButtonLaLibertadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLaLibertadActionPerformed
        try {
            pri.seleccionarDepartamento("La Libertad","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonLaLibertadActionPerformed

    private void jRadioButtonAncashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAncashActionPerformed
        try {
            pri.seleccionarDepartamento("Ancash","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonAncashActionPerformed

    private void jRadioButtonHuanucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHuanucoActionPerformed
        try {
            pri.seleccionarDepartamento("Huánuco","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonHuanucoActionPerformed

    private void jRadioButtonUcayaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUcayaliActionPerformed
        try {
            pri.seleccionarDepartamento("Ucayali","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonUcayaliActionPerformed

    private void jRadioButtonLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLimaActionPerformed
        try {
            pri.seleccionarDepartamento("Lima","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonLimaActionPerformed

    private void jRadioButtonIcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIcaActionPerformed
        try {
            pri.seleccionarDepartamento("Ica","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonIcaActionPerformed

    private void jRadioButtonArequipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonArequipaActionPerformed
        try {
            pri.seleccionarDepartamento("Arequipa","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonArequipaActionPerformed

    private void jRadioButtonAyacuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAyacuchoActionPerformed
        try {
            pri.seleccionarDepartamento("Ayacucho","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonAyacuchoActionPerformed

    private void jRadioButtonTacnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTacnaActionPerformed
        try {
            pri.seleccionarDepartamento("Tacna","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonTacnaActionPerformed

    private void jRadioButtonPunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPunoActionPerformed
        try {
            pri.seleccionarDepartamento("Puno","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonPunoActionPerformed

    private void jRadioButtonMadredeDiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMadredeDiosActionPerformed
        try {
            pri.seleccionarDepartamento("Madre de Dios","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonMadredeDiosActionPerformed

    private void jRadioButtonCuscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCuscoActionPerformed
        try {
            pri.seleccionarDepartamento("Cusco","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonCuscoActionPerformed

    private void jRadioButtonMoqueguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMoqueguaActionPerformed
        try {
            pri.seleccionarDepartamento("Moquegua","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonMoqueguaActionPerformed

    private void jRadioButtonApurimacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonApurimacActionPerformed
        try {
            pri.seleccionarDepartamento("Apurímac","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonApurimacActionPerformed

    private void jRadioButtonHuancavelicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHuancavelicaActionPerformed
        try {
            pri.seleccionarDepartamento("Huancavelica","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonHuancavelicaActionPerformed

    private void jRadioButtonPascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPascoActionPerformed
        try {
            pri.seleccionarDepartamento("Pasco","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonPascoActionPerformed

    private void jRadioButtonJuninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuninActionPerformed
        try {
            pri.seleccionarDepartamento("Junín","Cualquiera");
        } catch (SQLException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonJuninActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButtonAmazonas;
    private javax.swing.JRadioButton jRadioButtonAncash;
    private javax.swing.JRadioButton jRadioButtonApurimac;
    private javax.swing.JRadioButton jRadioButtonArequipa;
    private javax.swing.JRadioButton jRadioButtonAyacucho;
    private javax.swing.JRadioButton jRadioButtonCajamarca;
    private javax.swing.JRadioButton jRadioButtonCusco;
    private javax.swing.JRadioButton jRadioButtonHuancavelica;
    private javax.swing.JRadioButton jRadioButtonHuanuco;
    private javax.swing.JRadioButton jRadioButtonIca;
    private javax.swing.JRadioButton jRadioButtonJunin;
    private javax.swing.JRadioButton jRadioButtonLaLibertad;
    private javax.swing.JRadioButton jRadioButtonLambayeque;
    private javax.swing.JRadioButton jRadioButtonLima;
    private javax.swing.JRadioButton jRadioButtonLoreto;
    private javax.swing.JRadioButton jRadioButtonMadredeDios;
    private javax.swing.JRadioButton jRadioButtonMoquegua;
    private javax.swing.JRadioButton jRadioButtonPasco;
    private javax.swing.JRadioButton jRadioButtonPiura;
    private javax.swing.JRadioButton jRadioButtonPuno;
    private javax.swing.JRadioButton jRadioButtonSanMartin;
    private javax.swing.JRadioButton jRadioButtonTacna;
    private javax.swing.JRadioButton jRadioButtonTumbes;
    private javax.swing.JRadioButton jRadioButtonUcayali;
    // End of variables declaration//GEN-END:variables
}
