/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.Persona.menuPrincipales;

import edu.unmsm.sistemas.sgpy.Persona.controlador.ControladorCrudPersona;
import edu.unmsm.sistemas.sgpy.Persona.modelo.PersonaDAO;
import edu.unmsm.sistemas.sgpy.Persona.vista.*;
import edu.unmsm.sistemas.sgpy.Persona.modelo.*;
import edu.unmsm.sistemas.sgpy.Persona.controlador.*;
/**
 *
 * @author Raul Emilio
 */
public class OpcionesFrmPersona extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesFrm
     */
    public OpcionesFrmPersona() {
        initComponents();
    }
    public OpcionesFrmPersona(String nombre) {
        
        initComponents();
        EBienvenida.setText("Bienvenido "+nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegistrarPersona = new javax.swing.JButton();
        btnModificarPersona = new javax.swing.JButton();
        btnEliminarPersona = new javax.swing.JButton();
        btnVisualizarPersona = new javax.swing.JButton();
        EBienvenida = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Opciones");

        btnRegistrarPersona.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrarPersona.setText("Agregar Persona");
        btnRegistrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonaActionPerformed(evt);
            }
        });

        btnModificarPersona.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificarPersona.setText("Modificar Persona");
        btnModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPersonaActionPerformed(evt);
            }
        });

        btnEliminarPersona.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminarPersona.setText("Eliminar Persona");
        btnEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonaActionPerformed(evt);
            }
        });

        btnVisualizarPersona.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVisualizarPersona.setText("Visualizar Persona");
        btnVisualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarPersonaActionPerformed(evt);
            }
        });

        EBienvenida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EBienvenida.setText("Bienvenido");

        botonVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(EBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnModificarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisualizarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonaActionPerformed
        JFAgregarPersona frame1 = new JFAgregarPersona();
        PersonaDAO modelo = new PersonaDAO();
        ControladorCrudPersona controlador = new ControladorCrudPersona(frame1,modelo);
        
        frame1.setVisible(true);
        frame1.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_btnRegistrarPersonaActionPerformed

    private void btnModificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPersonaActionPerformed
        JFModificarPersona frame2 = new JFModificarPersona();
        PersonaDAO modelo = new PersonaDAO();
        ControladorCrudPersona controlador = new ControladorCrudPersona(frame2,modelo);
        
        frame2.setVisible(true);
        frame2.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_btnModificarPersonaActionPerformed

    private void btnEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonaActionPerformed
        JFEliminarPersona frame3 = new JFEliminarPersona();
        PersonaDAO modelo = new PersonaDAO();
        ControladorCrudPersona controlador = new ControladorCrudPersona(frame3,modelo);
        
        frame3.setVisible(true);
        frame3.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_btnEliminarPersonaActionPerformed

    private void btnVisualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarPersonaActionPerformed
        JFVisualizarPersona frame4=new JFVisualizarPersona();
        PersonaDAO modelo = new PersonaDAO();
        ControladorCrudPersona controlador = new ControladorCrudPersona(frame4,modelo);
        
        frame4.setLocationRelativeTo(null);
        frame4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVisualizarPersonaActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        OpcionesFrmPersona frame4=new OpcionesFrmPersona();
        OpcionesPrincipal frame = new OpcionesPrincipal();
        frame4.setVisible(false);
        this.dispose();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesFrmPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EBienvenida;
    public javax.swing.JButton botonVolver;
    private javax.swing.JButton btnEliminarPersona;
    private javax.swing.JButton btnModificarPersona;
    private javax.swing.JButton btnRegistrarPersona;
    private javax.swing.JButton btnVisualizarPersona;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
