/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Profesion;

import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo.Profesion;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo_DAO.ProfesionDAO;
import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Principal.I_MenuProfesion;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class I_EliminarProfesion extends javax.swing.JFrame {
    ResultSet rs;
    Profesion pr=new Profesion();
    ProfesionDAO prd=new ProfesionDAO();

    /**
     * Creates new form FrameEliminarProfesion
     */
    public I_EliminarProfesion() {
        initComponents();
        this.setSize(600, 500);
        this.setTitle("Eliminar Profesión");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jBEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuRegistrar = new javax.swing.JMenuItem();
        jMenuModificar = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFieldCodigoBE = new javax.swing.JTextField();
        jBBuscarE = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTFieldCodigoE = new javax.swing.JTextField();
        jTFieldNombreE = new javax.swing.JTextField();
        jBEliminar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTFieldGradoE = new javax.swing.JTextField();
        jTFieldAreaE = new javax.swing.JTextField();
        btnSalirM = new javax.swing.JButton();

        jMenuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoRegistrarProfesion.png"))); // NOI18N
        jMenuRegistrar.setText("Registrar Profesion");
        jMenuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuRegistrar);

        jMenuModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoiModificarProfesion.png"))); // NOI18N
        jMenuModificar.setText("Modificar Profesion");
        jMenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuModificar);

        jMenuListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoLista.png"))); // NOI18N
        jMenuListar.setText("Listar Profesión");
        jMenuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuListar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Profesion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel5.setComponentPopupMenu(jPopupMenu);

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel16.setText("Ingrese Código:");
        jLabel16.setOpaque(true);

        jTFieldCodigoBE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFieldCodigoBEKeyTyped(evt);
            }
        });

        jBBuscarE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBBuscarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoBuscar.png"))); // NOI18N
        jBBuscarE.setText("Buscar");
        jBBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarEActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel18.setText("Nombre de Profesión:");
        jLabel18.setOpaque(true);

        jLabel19.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel19.setText("Grado de Profesión:");
        jLabel19.setOpaque(true);

        jLabel21.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel21.setText("Área de Profesión:");
        jLabel21.setOpaque(true);

        jTFieldCodigoE.setEditable(false);

        jTFieldNombreE.setEditable(false);

        jBEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoEliminarProfesion.png"))); // NOI18N
        jBEliminar.setText("ELIMINAR");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel20.setText("Código de Profesión:");
        jLabel20.setOpaque(true);

        jTFieldGradoE.setEditable(false);

        jTFieldAreaE.setEditable(false);

        btnSalirM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoSalir.png"))); // NOI18N
        btnSalirM.setText("SALIR");
        btnSalirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel16))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTFieldCodigoE, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFieldGradoE, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFieldNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFieldAreaE, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jTFieldCodigoBE, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscarE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jBEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalirM)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFieldCodigoBE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFieldCodigoE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFieldNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFieldGradoE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFieldAreaE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirM))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarEActionPerformed
          Profesion pf;
          String nombreGrado;
        int indiceG,indiceA;
        jTFieldCodigoE.setEditable(false);
        if(jTFieldCodigoBE.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Llene el codigo a Buscar","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        else{
            if(jTFieldCodigoBE.getText().length()!=5){
                JOptionPane.showMessageDialog(null,"Tamaño de codigo no valido","Advertencia",JOptionPane.WARNING_MESSAGE);
                jTFieldCodigoBE.setBackground(Color.red);
                jTFieldCodigoBE.setText("");
            }else{
                jBEliminar.setEnabled(true);
                try {  
                        pf=buscarProfesion(jTFieldCodigoBE.getText());
                        if(pf!=null){
                            jTFieldCodigoE.setText(String.valueOf(pf.getCodigo_Profesion()));
                            jTFieldNombreE.setText(pf.getNombre_Profesion());
                            nombreGrado=retornarNombreGrado(pf.getGrado_Profesion());
                            jTFieldGradoE.setText(nombreGrado);
                            jTFieldAreaE.setText(pf.getArea());
                            jTFieldCodigoBE.setText("");
                        }else{
                             JOptionPane.showMessageDialog(rootPane, "PROFESION NO ENCONTRADA", "NOTIFICACIÓN", JOptionPane.INFORMATION_MESSAGE);

                        }

                } catch (Exception ex) {
                    Logger.getLogger(I_ListarProfesion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jBBuscarEActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        String nombGrado;
        pr.setCodigo_Profesion(Integer.parseInt(jTFieldCodigoE.getText()));
        nombGrado=retornarSiglaGrado(jTFieldGradoE.getText());
        pr.setGrado_Profesion(nombGrado);
        pr.setNombre_Profesion(jTFieldNombreE.getText());
        pr.setArea(jTFieldAreaE.getText());
        pr.setVigente("0");
        prd.Modificar(pr);
        JOptionPane.showMessageDialog(null,"Profesion Eliminada","Eliminar",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTFieldCodigoBEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFieldCodigoBEKeyTyped
         char car = evt.getKeyChar();
         if(((car< '0') ||(car > '9')) )
        {
           evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jTFieldCodigoBEKeyTyped

    private void btnSalirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMActionPerformed
        new I_MenuProfesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirMActionPerformed

    private void jMenuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrarActionPerformed
        I_RegistrarProfesion rp=new I_RegistrarProfesion();
        rp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuRegistrarActionPerformed

    private void jMenuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarActionPerformed
        I_ModificarProfesion mp=new I_ModificarProfesion();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuModificarActionPerformed

    private void jMenuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarActionPerformed
        I_ListarProfesion mp=new I_ListarProfesion ();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuListarActionPerformed

    
    public String retornarNombre(String descripcion){
        String nombre = "";
        for(int i=0;i<descripcion.length();i++){
            if(descripcion.charAt(i)== '/'){
                break;
            }
            nombre=nombre + descripcion.charAt(i);
        }
        return nombre;
    }
    
    public String retornarArea(String descripcion){
        String area = "";
        for(int i=0;i<descripcion.length();i++){
            if(descripcion.charAt(i)== '/'){
               for(int j=i+1;j<descripcion.length();j++){
                   area=area+ descripcion.charAt(j);
               }
               break;
            }
        }
        return area;
    }
    
    public Profesion buscarProfesion(String codigo) throws Exception{
          boolean bandera=false;
          String nombre,area;
          Profesion pf=new Profesion();
          rs=prd.listarPorVigencia("1");
          while(rs.next()){
                if(rs.getString(1).equals(codigo) && rs.getString(4).equals("1") ){
                    pf.setCodigo_Profesion(rs.getInt(1));
                    pf.setGrado_Profesion(rs.getString(2));
                    nombre=retornarNombre(rs.getString(3));
                    area=retornarArea(rs.getString(3));
                    pf.setNombre_Profesion(nombre);
                    pf.setArea(area);
                    bandera=true;
                }
           }
           
           if(!bandera){
               return null;
           }
           else{
               return pf;
           }   
     }
    
     public String retornarSiglaGrado(String grado){
        String nomGrado="";
        switch(grado){
            case "Técnico" : nomGrado="T";
                              break; 
            case "Bachiller":nomGrado="B";
                              break; 
            case "Título Profesional":nomGrado="P";
                                      break; 
            case "Maestría":nomGrado="M";
                                      break; 
            case "Doctorado":nomGrado="D";
                                      break; 
            case "Post-Doctorado":nomGrado="H";
                                      break; 
        }
        return nomGrado;
    }
    
    public String retornarNombreGrado(String grado){
        String nomGrado="";
        switch(grado){
            case "T" : nomGrado="Técnico";
                              break; 
            case "B":nomGrado="Bachiller";
                              break; 
            case "P":nomGrado="Título Profesional";
                                      break; 
            case "M":nomGrado="Maestría";
                                      break; 
            case "D":nomGrado="Doctorado";
                                      break; 
            case "H":nomGrado="post-Doctorado";
                                      break; 
        }
        return nomGrado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_EliminarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_EliminarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_EliminarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_EliminarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_EliminarProfesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirM;
    private javax.swing.JButton jBBuscarE;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JMenuItem jMenuListar;
    private javax.swing.JMenuItem jMenuModificar;
    private javax.swing.JMenuItem jMenuRegistrar;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JTextField jTFieldAreaE;
    private javax.swing.JTextField jTFieldCodigoBE;
    private javax.swing.JTextField jTFieldCodigoE;
    private javax.swing.JTextField jTFieldGradoE;
    private javax.swing.JTextField jTFieldNombreE;
    // End of variables declaration//GEN-END:variables
}
