/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Profesion;

import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo.Profesion;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo_DAO.ProfesionDAO;
import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Principal.I_MenuProfesion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casa
 */
public class I_ListarProfesion extends javax.swing.JFrame {

    /**
     * Creates new form I_ListarProfesion
     */
    Profesion pr=new Profesion();
    ProfesionDAO prd=new ProfesionDAO();
    Object obj[] =new Object[5] ;
    DefaultTableModel modeloTabla;
    DefaultTableModel m;
    JTable tabla_Profesion;
    ResultSet rs;
    String habilitados="";
    
    public I_ListarProfesion() {
       initComponents();
       this.setLocationRelativeTo(null);
       this.setResizable(false);
       this.setSize(665, 460);
       this.setTitle("Profesión");
       jBHabilitar.setVisible(false);
     }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuRegistrar = new javax.swing.JMenuItem();
        jMenuEliminar = new javax.swing.JMenuItem();
        jMenuModificar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jBListar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jBHabilitar = new javax.swing.JButton();
        btnSalirM = new javax.swing.JButton();

        jMenuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoRegistrarProfesion.png"))); // NOI18N
        jMenuRegistrar.setText("Registrar Profesion");
        jMenuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuRegistrar);

        jMenuEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoEliminarProfesion.png"))); // NOI18N
        jMenuEliminar.setText("Eliminar Profesion");
        jMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuEliminar);

        jMenuModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoiModificarProfesion.png"))); // NOI18N
        jMenuModificar.setText("Modificar Profesion");
        jMenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuModificar);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Profesiones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel2.setComponentPopupMenu(jPopupMenu);

        jBListar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoLista.png"))); // NOI18N
        jBListar.setText("LISTAR");
        jBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Habilitado");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Deshabilitado");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        jBHabilitar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBHabilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconHabilitar.png"))); // NOI18N
        jBHabilitar.setText("Habilitar");
        jBHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHabilitarActionPerformed(evt);
            }
        });

        btnSalirM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoSalir.png"))); // NOI18N
        btnSalirM.setText("SALIR");
        btnSalirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jBListar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSalirM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBHabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jBListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBHabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirM))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarActionPerformed
       String nombre,area,nombreGrado;
       modeloTabla = new DefaultTableModel();
       modeloTabla.addColumn("Codigo");
       modeloTabla.addColumn("Grado");
       modeloTabla.addColumn("Nombre de Profesion");
       modeloTabla.addColumn("Area");
       modeloTabla.addColumn("Habilitado");
        if(habilitados.equals("Habilitado")){
                try {
                    rs = prd.listarPorVigencia("1");
                    while(rs.next()){
                        obj[0]=rs.getString(1);
                        nombreGrado=rs.getString(2);
                        obj[1]=retornarNombreGrado(nombreGrado);
                        nombre=retornarNombre(rs.getString(3));
                        area=retornarArea(rs.getString(3));
                        obj[2]=nombre;
                        obj[3]=area;
                        obj[4]="✓";
                        modeloTabla.addRow(obj);
                    }
                    tabla_Profesion = new JTable();
                    tabla_Profesion.setModel(modeloTabla);
                    tabla_Profesion.getTableHeader().setReorderingAllowed(false);
                    tabla_Profesion.getColumnModel().getColumn(0).setMaxWidth(50);
                    tabla_Profesion.getColumnModel().getColumn(1).setMaxWidth(150);
                    tabla_Profesion.getColumnModel().getColumn(2).setMaxWidth(150);
                    tabla_Profesion.getColumnModel().getColumn(3).setMaxWidth(150);
                    tabla_Profesion.getColumnModel().getColumn(4).setMaxWidth(50);
                    DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
                    modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
                    for (int i = 0; i < tabla_Profesion.getColumnCount(); i++) {
                        tabla_Profesion.getColumnModel().getColumn(i).setCellRenderer(modelocentrar);
                    }
                    jScrollPane2.setViewportView(tabla_Profesion);
              
                    habilitados="";
                } catch (Exception ex) {
                    Logger.getLogger(I_ListarProfesion.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else{
            if(habilitados.equals("Deshabilitado")){
                    try {
                        rs = prd.listarPorVigencia("0");
                         while(rs.next()){
                                obj[0]=rs.getString(1);
                                nombreGrado=rs.getString(2);
                                obj[1]=retornarNombreGrado(nombreGrado);
                                nombre=retornarNombre(rs.getString(3));
                                area=retornarArea(rs.getString(3));
                                obj[2]=nombre;
                                obj[3]=area;
                                obj[4]="x";
                                modeloTabla.addRow(obj);
                        }
                        tabla_Profesion = new JTable();
                        tabla_Profesion.setModel(modeloTabla);
                        tabla_Profesion.getTableHeader().setReorderingAllowed(false);
                        tabla_Profesion.getColumnModel().getColumn(0).setMaxWidth(50);
                        tabla_Profesion.getColumnModel().getColumn(1).setMaxWidth(130);
                        tabla_Profesion.getColumnModel().getColumn(2).setMaxWidth(130);
                        tabla_Profesion.getColumnModel().getColumn(3).setMaxWidth(130);
                        tabla_Profesion.getColumnModel().getColumn(4).setMaxWidth(100);
                        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
                        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
                        for (int i = 0; i < tabla_Profesion.getColumnCount(); i++) {
                            tabla_Profesion.getColumnModel().getColumn(i).setCellRenderer(modelocentrar);
                        }
                        jScrollPane2.setViewportView(tabla_Profesion);
                        habilitados="";
                        jBHabilitar.setVisible(true);//Activa boton Habilitar
                    }catch (Exception ex) {
                       Logger.getLogger(I_ListarProfesion.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }else{
                     try {
                        rs=prd.listarPorVigencia("1");
                        while(rs.next()){
                            obj[0]=rs.getInt(1);
                            nombreGrado=rs.getString(2);
                            obj[1]=retornarNombreGrado(nombreGrado);
                            nombre=retornarNombre(rs.getString(3));
                            area=retornarArea(rs.getString(3));
                            obj[2]=nombre;
                            obj[3]=area;
                            if(rs.getString(4).equals("1")){
                                  obj[4]="✓";
                            }else{
                                 jBHabilitar.setVisible(true);
                                 obj[4]="x";
                            }
                            modeloTabla.addRow(obj);
                        }
                        tabla_Profesion = new JTable();
                        tabla_Profesion.setModel(modeloTabla);
                        tabla_Profesion.getTableHeader().setReorderingAllowed(false);
                        tabla_Profesion.getColumnModel().getColumn(0).setMaxWidth(50);
                        tabla_Profesion.getColumnModel().getColumn(1).setMaxWidth(130);
                        tabla_Profesion.getColumnModel().getColumn(2).setMaxWidth(130);
                        tabla_Profesion.getColumnModel().getColumn(3).setMaxWidth(130);
                        tabla_Profesion.getColumnModel().getColumn(4).setMaxWidth(100);
                        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer(); 
                        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER); 
                        for(int i=0;i<tabla_Profesion.getColumnCount();i++){
                              tabla_Profesion.getColumnModel().getColumn(i).setCellRenderer(modelocentrar);
                    }
                        jScrollPane2.setViewportView(tabla_Profesion);
                        jBHabilitar.setVisible(true);// Activa boton Habilitar
                    }catch (Exception ex) {
                            Logger.getLogger(I_ListarProfesion.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }  
        }
    }//GEN-LAST:event_jBListarActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
            habilitados=jRadioButton1.getLabel();
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
           habilitados=jRadioButton2.getLabel();
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jBHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHabilitarActionPerformed
    int fselec= tabla_Profesion.getSelectedRow();
    if(fselec==-1){
               JOptionPane.showMessageDialog(null,"Debe seleccionar un profesion","Advertencia",JOptionPane.WARNING_MESSAGE);
    }else{
         String nombGrado;
         pr.setCodigo_Profesion(Integer.parseInt(tabla_Profesion.getValueAt(fselec, 0).toString() ));
         nombGrado=retornarSiglaGrado( tabla_Profesion.getValueAt(fselec, 1).toString() );
         pr.setGrado_Profesion(nombGrado);
         pr.setNombre_Profesion( tabla_Profesion.getValueAt(fselec, 2).toString() );
         pr.setArea( tabla_Profesion.getValueAt(fselec, 3).toString() );
         pr.setVigente("1");
         prd.Modificar(pr);
         JOptionPane.showMessageDialog(null,"Profesion habilitada","Eliminar",JOptionPane.INFORMATION_MESSAGE);   
         jBHabilitar.setVisible(false);
   }       
    }//GEN-LAST:event_jBHabilitarActionPerformed

    private void jMenuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrarActionPerformed
        I_RegistrarProfesion rp=new I_RegistrarProfesion();
        rp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuRegistrarActionPerformed

    private void jMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarActionPerformed
        I_EliminarProfesion ep=new I_EliminarProfesion();
        ep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuEliminarActionPerformed

    private void jMenuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarActionPerformed
        I_ModificarProfesion mp=new I_ModificarProfesion();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuModificarActionPerformed

    private void btnSalirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMActionPerformed
        new I_MenuProfesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirMActionPerformed
    
    public String retornarSiglaGrado(String grado){
        String nomGrado="";
        switch(grado){
            case "Técnico" : nomGrado="T";
                              break; 
            case "Bachiller":nomGrado="B";
                              break; 
            case "Título Profesional":nomGrado="P";
                                      break; 
            case "Maestría":nomGrado="M";
                                      break; 
            case "Doctorado":nomGrado="D";
                                      break; 
            case "Post-Doctorado":nomGrado="H";
                                      break; 
        }
        return nomGrado;
    }
    
      public String retornarNombreGrado(String grado){
        String nomGrado="";
        switch(grado){
            case "T" : nomGrado="Técnico";
                              break; 
            case "B":nomGrado="Bachiller";
                              break; 
            case "P":nomGrado="Título Profesional";
                                      break; 
            case "M":nomGrado="Maestría";
                                      break; 
            case "D":nomGrado="Doctorado";
                                      break; 
            case "H":nomGrado="post-Doctorado";
                                      break; 
        }
        return nomGrado;
    }
    
    public String retornarNombre(String descripcion){
        String nombre = "";
        for(int i=0;i<descripcion.length();i++){
            if(descripcion.charAt(i)== '/'){
                break;
            }
            nombre=nombre + descripcion.charAt(i);
        }
        return nombre;
    }
    
    public String retornarArea(String descripcion){
        String area = "";
        for(int i=0;i<descripcion.length();i++){
            if(descripcion.charAt(i)== '/'){
               for(int j=i+1;j<descripcion.length();j++){
                   area=area+ descripcion.charAt(j);
               }
               break;
            }
        }
        return area;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_ListarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_ListarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_ListarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_ListarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new I_ListarProfesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirM;
    public static javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBHabilitar;
    private javax.swing.JButton jBListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuEliminar;
    private javax.swing.JMenuItem jMenuModificar;
    private javax.swing.JMenuItem jMenuRegistrar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

 
}
