/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Profesion;

import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Profesion.I_EliminarProfesion;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo.Profesion;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo_DAO.ProfesionDAO;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo_LN.ProfesionLN;
import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Principal.I_MenuProfesion;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class I_ModificarProfesion extends javax.swing.JFrame {

    /**
     * Creates new form I_ModificarProfesion
     */
    ResultSet rs;
    Profesion pr=new Profesion();
    ProfesionDAO prd=new ProfesionDAO();
    ProfesionLN prln = new ProfesionLN(); 
    
    public I_ModificarProfesion() {
        initComponents();
        this.setSize(655, 525);
        this.setTitle("Modificar Profesión");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jBModificar.setEnabled(false);
        jTFieldCodigoBM.setEditable(true);
        jTFieldCodigoM.setEditable(false);
        jComboBoxAreaM.setEnabled(false);
        jComboBoxGradoM.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuRegistrar = new javax.swing.JMenuItem();
        jMenuEliminar = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTFieldCodigoM = new javax.swing.JTextField();
        jBBuscarM = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jTFieldCodigoBM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxGradoM = new javax.swing.JComboBox();
        jTFieldNombreM = new javax.swing.JTextField();
        jComboBoxAreaM = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        btnSalirM = new javax.swing.JButton();

        jMenuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoRegistrarProfesion.png"))); // NOI18N
        jMenuRegistrar.setText("Registrar Profesion");
        jMenuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuRegistrar);

        jMenuEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoEliminarProfesion.png"))); // NOI18N
        jMenuEliminar.setText("Eliminar Profesion");
        jMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuEliminar);

        jMenuListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoLista.png"))); // NOI18N
        jMenuListar.setText("Listar Profesión");
        jMenuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuListar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Profesion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel4.setComponentPopupMenu(jPopupMenu);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Ingrese Código:");
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel10.setText("Nombre de Profesión:");
        jLabel10.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel11.setText("Grado de Profesión:");
        jLabel11.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel13.setText("Área de Profesión:");
        jLabel13.setOpaque(true);

        jTFieldCodigoM.setEditable(false);

        jBBuscarM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBBuscarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoBuscar.png"))); // NOI18N
        jBBuscarM.setText("Buscar");
        jBBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarMActionPerformed(evt);
            }
        });

        jBModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoiModificarProfesion.png"))); // NOI18N
        jBModificar.setText("MODIFICAR");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jTFieldCodigoBM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFieldCodigoBMKeyTyped(evt);
            }
        });

        jComboBoxGradoM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "   -SELECCIONE GRADO-", "Técnico", "Bachiller", "Título Profesional", "Maestría", "Doctorado", "Post-Doctorado" }));

        jTFieldNombreM.setEditable(false);

        jComboBoxAreaM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    - SELECCIONE ÁREA-", "Ciencias Básicas", "Ingenierías", "Económico Empresarial" }));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel7.setText("Código de Profesión:");
        jLabel7.setOpaque(true);

        btnSalirM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoSalir.png"))); // NOI18N
        btnSalirM.setText("SALIR");
        btnSalirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFieldCodigoBM, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscarM))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnSalirM))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxGradoM, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFieldNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxAreaM, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFieldCodigoM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jBModificar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel14)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTFieldCodigoBM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarM))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFieldCodigoM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFieldNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxGradoM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAreaM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModificar)
                    .addComponent(btnSalirM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarMActionPerformed
        Profesion pf;
        int indiceG,indiceA;
        if(jTFieldCodigoBM.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Llene el codigo a Buscar","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        else{
            if(jTFieldCodigoBM.getText().length()!=5){
                JOptionPane.showMessageDialog(null,"Tamaño de codigo no valido","Advertencia",JOptionPane.WARNING_MESSAGE);
                jTFieldCodigoBM.setBackground(Color.red);
                jTFieldCodigoBM.setText("");
            }else{
                jBModificar.setEnabled(true);
                try {
                    pf=prln.buscarProfesion(jTFieldCodigoBM.getText());
                    if(pf!=null){
                        jComboBoxAreaM.setEnabled(true);
                        jComboBoxGradoM.setEnabled(true);
                        jTFieldNombreM.setEditable(true);
                        jTFieldCodigoM.setText(String.valueOf(pf.getCodigo_Profesion()));
                        jTFieldNombreM.setText(pf.getNombre_Profesion());
                        indiceG=retornarIndiceGrado(pf.getGrado_Profesion());
                        jComboBoxGradoM.setSelectedIndex(indiceG);
                        indiceA=retornarIndiceArea(pf.getArea());
                        jComboBoxAreaM.setSelectedIndex(indiceA);
                        jTFieldCodigoBM.setText("");
                    }else{
                          JOptionPane.showMessageDialog(rootPane, "PROFESION NO ENCONTRADA", "NOTIFICACIÓN", JOptionPane.INFORMATION_MESSAGE);
                          jTFieldCodigoBM.setText("");
                    }
                    
                    
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jBBuscarMActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        jTFieldCodigoBM.setBackground(Color.WHITE);
        String grado;
        if(jTFieldNombreM.getText().equals("")){
            jTFieldNombreM.setBackground(Color.red);
        }else{
            jTFieldNombreM.setBackground(Color.WHITE);
        }

        if(  (jComboBoxGradoM.getSelectedIndex()==0 || jComboBoxGradoM.getSelectedIndex()==-1)){
            jComboBoxGradoM.setBackground(Color.red);
        }else{
            jComboBoxGradoM.setBackground(Color.WHITE);
        }

        if((jComboBoxAreaM.getSelectedIndex()==0 || jComboBoxAreaM.getSelectedIndex()==-1)){
            jComboBoxAreaM.setBackground(Color.red);
        }else{
            jComboBoxAreaM.setBackground(Color.WHITE);
        }

        if( jTFieldNombreM.getText().equals("") ||
            (jComboBoxGradoM.getSelectedIndex()==0 || jComboBoxGradoM.getSelectedIndex()==-1) ||
            (jComboBoxAreaM.getSelectedIndex()==0 || jComboBoxAreaM.getSelectedIndex()==-1) ){
            JOptionPane.showMessageDialog(null,"Complete campos señalados","Advertencia",JOptionPane.WARNING_MESSAGE);
        }else{
            pr.setCodigo_Profesion(Integer.parseInt(jTFieldCodigoM.getText()));
            grado = retornarNombreGrado(jComboBoxGradoM.getSelectedItem().toString());
            pr.setGrado_Profesion(grado);
            pr.setNombre_Profesion(jTFieldNombreM.getText());
            pr.setArea(jComboBoxAreaM.getSelectedItem().toString());
            pr.setVigente("1");
            prd.Modificar(pr);
            JOptionPane.showMessageDialog(null,"Profesion Modificada","Modificar",JOptionPane.INFORMATION_MESSAGE);
            jTFieldNombreM.setText("");
            jTFieldCodigoM.setText("");
            jTFieldCodigoBM.setText("");
            jComboBoxGradoM.setSelectedIndex(0);
            jComboBoxAreaM.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jTFieldCodigoBMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFieldCodigoBMKeyTyped
        char car = evt.getKeyChar();
         if(((car< '0') ||(car > '9')) )
        {
           evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jTFieldCodigoBMKeyTyped

    private void btnSalirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMActionPerformed
        this.dispose();
        new I_MenuProfesion().setVisible(true);
    }//GEN-LAST:event_btnSalirMActionPerformed

    private void jMenuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrarActionPerformed
        this.dispose();
        I_RegistrarProfesion rp=new I_RegistrarProfesion();
        rp.setVisible(true);
    }//GEN-LAST:event_jMenuRegistrarActionPerformed

    private void jMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarActionPerformed
        this.dispose();
        I_EliminarProfesion ep=new I_EliminarProfesion();
        ep.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarActionPerformed

    private void jMenuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarActionPerformed
        I_ListarProfesion mp=new I_ListarProfesion ();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuListarActionPerformed

    public String retornarNombre(String descripcion){
        String nombre = "";
        for(int i=0;i<descripcion.length();i++){
            if(descripcion.charAt(i)== '/'){
                break;
            }
            nombre=nombre + descripcion.charAt(i);
        }
        return nombre;
    }
    
    public String retornarArea(String descripcion){
        String area = "";
        for(int i=0;i<descripcion.length();i++){
            if(descripcion.charAt(i)== '/'){
               for(int j=i+1;j<descripcion.length();j++){
                   area=area+ descripcion.charAt(j);
               }
               break;
            }
        }
        return area;
    }
    
    
     
    public int retornarIndiceGrado(String nomGrado){
        int index=0;
        switch(nomGrado){
            case "T": index=1;
                                    break;
            case "B": index=2;
                                    break;
            case "P": index=3;
                                    break;
            case "M": index=4;
                                    break;
            case "D": index=5;
                                    break;
            case "H": index=6;
                                    break;
       }
        return index;
    }
    
    public int retornarIndiceArea(String nomArea){
        int index=0;
       switch(nomArea){
            case "Ciencias Básicas": index=1;
                                    break;
            case "Ingenierías": index=2;
                                    break;
            case "Económico Empresarial": index=3;
                                          break;
       }
        
        return index;
    }
    
    public String retornarNombreGrado(String grado){
        String nomGrado="";
        switch(grado){
            case "Técnico" : nomGrado="T";
                              break; 
            case "Bachiller":nomGrado="B";
                              break; 
            case "Título Profesional":nomGrado="P";
                                      break; 
            case "Maestría":nomGrado="M";
                                      break; 
            case "Doctorado":nomGrado="D";
                                      break; 
            case "Post-Doctorado":nomGrado="H";
                                      break; 
        }
        return nomGrado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_ModificarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_ModificarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_ModificarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_ModificarProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_ModificarProfesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirM;
    private javax.swing.JButton jBBuscarM;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jComboBoxAreaM;
    private javax.swing.JComboBox jComboBoxGradoM;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuEliminar;
    private javax.swing.JMenuItem jMenuListar;
    private javax.swing.JMenuItem jMenuRegistrar;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JTextField jTFieldCodigoBM;
    private javax.swing.JTextField jTFieldCodigoM;
    private javax.swing.JTextField jTFieldNombreM;
    // End of variables declaration//GEN-END:variables
}
