/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.Persona.vista;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import edu.unmsm.sistemas.sgpy.Persona.menuPrincipales.OpcionesFrmComunicaciones;
import edu.unmsm.sistemas.sgpy.Persona.menuPrincipales.OpcionesFrmPersona;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Tics;

/**
 *
 * @author CARLOS
 */
public class JFAgregarTics extends javax.swing.JFrame {

    /**
     * Creates new form JFAgregarTics
     */
    public JFAgregarTics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargarFotoMenu = new javax.swing.JFileChooser();
        lblIcono = new javax.swing.JLabel();
        comboVigenciaTics = new javax.swing.JComboBox<>();
        btnRegistrarTics = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCargarImagen = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        textDescripcionTics = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tics");
        setMinimumSize(new java.awt.Dimension(745, 515));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 180, 180));

        comboVigenciaTics.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        comboVigenciaTics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No vigente", "Vigente" }));
        getContentPane().add(comboVigenciaTics, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        btnRegistrarTics.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRegistrarTics.setText("Registrar");
        getContentPane().add(btnRegistrarTics, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Vigente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Icono :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 233, -1, -1));

        btnCargarImagen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCargarImagen.setText("Cargar");
        btnCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarImagenActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Descripción :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        getContentPane().add(textDescripcionTics, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, 28));

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel5.setText("Registrar Tics");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 26, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public FileInputStream archivo;
    public int longitudBytes;
    File archivo2;   
    public ArrayList<Tics>aux;
    private void btnCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarImagenActionPerformed
        int resultado;
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
        cargarFotoMenu.setFileFilter(filtro);
        resultado = cargarFotoMenu.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            try {
                archivo2 = cargarFotoMenu.getSelectedFile();
                archivo = new FileInputStream(archivo2);
                this.longitudBytes = (int) (cargarFotoMenu.getSelectedFile().length());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFAgregarPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
            archivo2 = cargarFotoMenu.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(archivo2.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblIcono.getWidth(), lblIcono.getHeight(), Image.SCALE_DEFAULT));
                lblIcono.setText(null);
                lblIcono.setIcon(icono);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen" + ex);
            }
        }
    }//GEN-LAST:event_btnCargarImagenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        OpcionesFrmComunicaciones frame = new OpcionesFrmComunicaciones();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAgregarTics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAgregarTics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAgregarTics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAgregarTics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAgregarTics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarImagen;
    public javax.swing.JButton btnRegistrarTics;
    private javax.swing.JFileChooser cargarFotoMenu;
    public javax.swing.JComboBox<String> comboVigenciaTics;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel lblIcono;
    public javax.swing.JTextField textDescripcionTics;
    // End of variables declaration//GEN-END:variables
}
