/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.Persona.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import edu.unmsm.sistemas.sgpy.Persona.menuPrincipales.OpcionesFrmCliente;
import edu.unmsm.sistemas.sgpy.Persona.menuPrincipales.OpcionesFrmMedioCom;
import edu.unmsm.sistemas.sgpy.Persona.menuPrincipales.OpcionesPrincipal;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Persona;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Tics;

/**
 *
 * @author Branco
 */
public class JFAgregarMedioCom extends javax.swing.JFrame {

    /**
     * Creates new form JFPersonaTics
     */
    public JFAgregarMedioCom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonaTics1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTicPersona1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodPersona1 = new javax.swing.JTextField();
        jTextFieldCodTic1 = new javax.swing.JTextField();
        VisualizarPersona1 = new javax.swing.JButton();
        VisualizarTic1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDescripcion1 = new javax.swing.JTextField();
        ComboVigencia1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePersonaTics1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "DNI", "Cargo"
            }
        ));
        jTablePersonaTics1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonaTics1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonaTics1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 317, 94));

        jTableTicPersona1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodTic", "Descripcion"
            }
        ));
        jTableTicPersona1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTicPersona1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTicPersona1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 317, 93));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel1.setText("Código Persona:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 113, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel2.setText("Código Tic:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 182, -1, -1));
        jPanel1.add(jTextFieldCodPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 190, 26));
        jPanel1.add(jTextFieldCodTic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 190, 26));

        VisualizarPersona1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        VisualizarPersona1.setText("Visualizar Persona");
        jPanel1.add(VisualizarPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 198, -1, -1));

        VisualizarTic1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        VisualizarTic1.setText("Visualizar Tics");
        jPanel1.add(VisualizarTic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 140, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel3.setText("Descripción Medio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 262, -1, -1));
        jPanel1.add(jTextFieldDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 190, 26));

        ComboVigencia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Vigente", "Vigente" }));
        ComboVigencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboVigencia1ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboVigencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, 26));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel4.setText("Vigencia:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        botonRegistrar.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel5.setText("Registrar Medio de Comunicación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean bandera2=false;
    public ArrayList<Persona> aux;
    public ArrayList<Tics> aux1;
    public DefaultTableModel modelo1;
    public DefaultTableModel modelo2;
    public DefaultTableModel modelo3;
    public DefaultTableModel modelo4;
    
    private void ComboVigencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboVigencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboVigencia1ActionPerformed

    private void jTablePersonaTics1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonaTics1MouseClicked
        int fila = jTablePersonaTics1.rowAtPoint(evt.getPoint());
        jTextFieldCodPersona1.setEditable(true);
        jTextFieldCodPersona1.setText(String.valueOf(aux.get(fila).getCodPers()));
    }//GEN-LAST:event_jTablePersonaTics1MouseClicked

    private void jTableTicPersona1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTicPersona1MouseClicked
        int fila = jTableTicPersona1.rowAtPoint(evt.getPoint());
        jTextFieldCodTic1.setEditable(true);
        jTextFieldCodTic1.setText(String.valueOf(aux1.get(fila).getCodTics()));
    }//GEN-LAST:event_jTableTicPersona1MouseClicked

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        OpcionesFrmMedioCom frame = new OpcionesFrmMedioCom();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAgregarMedioCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAgregarMedioCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAgregarMedioCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAgregarMedioCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAgregarMedioCom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboVigencia1;
    public javax.swing.JButton VisualizarPersona1;
    public javax.swing.JButton VisualizarTic1;
    public javax.swing.JButton botonRegistrar;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTablePersonaTics1;
    public javax.swing.JTable jTableTicPersona1;
    public javax.swing.JTextField jTextFieldCodPersona1;
    public javax.swing.JTextField jTextFieldCodTic1;
    public javax.swing.JTextField jTextFieldDescripcion1;
    // End of variables declaration//GEN-END:variables
}
