/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.Persona.vista;

import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import edu.unmsm.sistemas.sgpy.Persona.menuPrincipales.OpcionesFrmPersona;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Departamento;
import edu.unmsm.sistemas.sgpy.Persona.modelo.DepartamentoDAO;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Distrito;
import edu.unmsm.sistemas.sgpy.Persona.modelo.DistritoDAO;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Persona;
import edu.unmsm.sistemas.sgpy.Persona.modelo.PersonaDAO;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Provincia;
import edu.unmsm.sistemas.sgpy.Persona.modelo.ProvinciaDAO;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Tics;
import edu.unmsm.sistemas.sgpy.Persona.modelo.TicsDAO;

/**
 *
 * @author CARLOS
 */
public class JFAgregarPersona extends javax.swing.JFrame {

    /**
     * Creates new form JFPersona2
     */
    public JFAgregarPersona() {
        initComponents();
        inicializarCombos();
        textCargo.setEnabled(false);
        comboVigencia.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargarFotoMenu = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        textHobby = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        jLabel46 = new javax.swing.JLabel();
        lblMostrarFoto = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        label156116 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        btnCargarFoto = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        labelLicencia = new javax.swing.JLabel();
        jspObservaciones2 = new javax.swing.JScrollPane();
        textObservaciones = new javax.swing.JTextArea();
        textDNI = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        textDescripcion2 = new javax.swing.JTextArea();
        textNROCIP = new javax.swing.JTextField();
        textCargo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        comboDistrito = new javax.swing.JComboBox<>();
        comboDepartamento = new javax.swing.JComboBox<>();
        comboProvincia = new javax.swing.JComboBox<>();
        comboTipoPersona = new javax.swing.JComboBox<>();
        comboLicencia = new javax.swing.JComboBox<>();
        radioCliente = new javax.swing.JRadioButton();
        radioBotonProfesional = new javax.swing.JRadioButton();
        radioBotonEspecialidad = new javax.swing.JRadioButton();
        fecNac = new com.toedter.calendar.JDateChooser();
        fecVigente = new com.toedter.calendar.JDateChooser();
        labelIconoMedios = new javax.swing.JLabel();
        comboVigencia = new javax.swing.JComboBox<>();
        botonVolver = new javax.swing.JButton();
        comboCargo = new javax.swing.JComboBox<>();
        comboCentroTrabajo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1007, 550));

        jPanel3.setPreferredSize(new java.awt.Dimension(933, 1132));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel17.setText("Registrar Persona");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 330, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Descripcion:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setText("Tipo Persona:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("Direccion:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 80, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel42.setText("Vigencia:");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 834, 60, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel43.setText("Descripcion Corta:");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, -1));
        jPanel3.add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 580, 26));

        textHobby.setColumns(20);
        textHobby.setRows(5);
        jScrollPane8.setViewportView(textHobby);

        jPanel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 580, 60));

        textDescripcion.setColumns(20);
        textDescripcion.setRows(5);
        jScrollPane9.setViewportView(textDescripcion);

        jPanel3.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 530, 50));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel46.setText("Fecha CIP Vigente:");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 685, 130, -1));

        lblMostrarFoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMostrarFoto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblMostrarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 170, 170));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel47.setText("Departamento: ");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 625, 110, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel48.setText("DNI:");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 565, 40, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel49.setText("Nro. CIP: ");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 685, 70, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel50.setText("Distrito:");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 625, 70, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel51.setText("Centro de Trabajo:");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 743, 180, -1));

        label156116.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        label156116.setText("Cargo:");
        jPanel3.add(label156116, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 745, 50, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel53.setText("Fecha de Nacimiento:");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 565, 140, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel55.setText("Provincia:");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 625, 70, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel56.setText("Hobby:");
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 70, -1));

        btnCargarFoto.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btnCargarFoto.setText("<html><p>Cargar</p><p align=center>foto</p></html>");
        btnCargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarFotoActionPerformed(evt);
            }
        });
        jPanel3.add(btnCargarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel57.setText("Observaciones:");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 890, 100, -1));

        labelLicencia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelLicencia.setText("Licencia Conducir:");
        jPanel3.add(labelLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 834, 180, -1));

        textObservaciones.setColumns(20);
        textObservaciones.setRows(5);
        jspObservaciones2.setViewportView(textObservaciones);

        jPanel3.add(jspObservaciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 890, 520, 130));

        textDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDNIKeyTyped(evt);
            }
        });
        jPanel3.add(textDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 150, 26));

        textDescripcion2.setColumns(20);
        textDescripcion2.setRows(5);
        jScrollPane10.setViewportView(textDescripcion2);

        jPanel3.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 530, 60));
        jPanel3.add(textNROCIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, 150, 26));
        jPanel3.add(textCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 780, 170, 26));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 1060, -1, -1));

        jPanel3.add(comboDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 190, 26));

        comboDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDepartamentoActionPerformed(evt);
            }
        });
        jPanel3.add(comboDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 120, 26));

        comboProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProvinciaActionPerformed(evt);
            }
        });
        jPanel3.add(comboProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, 160, 26));

        comboTipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Jurídico" }));
        comboTipoPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPersonaActionPerformed(evt);
            }
        });
        jPanel3.add(comboTipoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 100, 26));

        comboLicencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No posee", "Posee" }));
        comboLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLicenciaActionPerformed(evt);
            }
        });
        jPanel3.add(comboLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 830, 180, 26));

        radioCliente.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        radioCliente.setText("Cliente");
        radioCliente.setOpaque(false);
        radioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioClienteActionPerformed(evt);
            }
        });
        jPanel3.add(radioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 100, -1));

        radioBotonProfesional.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        radioBotonProfesional.setText("Profesional");
        radioBotonProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonProfesionalActionPerformed(evt);
            }
        });
        jPanel3.add(radioBotonProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        radioBotonEspecialidad.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        radioBotonEspecialidad.setText("Especialidad");
        radioBotonEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonEspecialidadActionPerformed(evt);
            }
        });
        jPanel3.add(radioBotonEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));
        jPanel3.add(fecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 170, 26));
        jPanel3.add(fecVigente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, 170, 26));
        jPanel3.add(labelIconoMedios, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 840, 130, 100));

        comboVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No vigente", "Vigente" }));
        jPanel3.add(comboVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 830, 170, 26));

        botonVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jPanel3.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1060, -1, -1));

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente general", "Gerente infraestructura", "Otro" }));
        comboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCargoActionPerformed(evt);
            }
        });
        jPanel3.add(comboCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 740, 170, 26));

        jPanel3.add(comboCentroTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 740, 180, 26));

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean bandera2=false;
    public FileInputStream archivo;
    File archivo2;
    public int longitudBytes;
    private void btnCargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarFotoActionPerformed
        int resultado;
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
        cargarFotoMenu.setFileFilter(filtro);
        resultado = cargarFotoMenu.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            try {
                archivo2 = cargarFotoMenu.getSelectedFile();
                archivo = new FileInputStream(archivo2);
                this.longitudBytes = (int) (cargarFotoMenu.getSelectedFile().length());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFAgregarPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
            archivo2 = cargarFotoMenu.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(archivo2.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblMostrarFoto.getWidth(), lblMostrarFoto.getHeight(), Image.SCALE_DEFAULT));
                lblMostrarFoto.setText(null);
                lblMostrarFoto.setIcon(icono);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen" + ex);
            }
        }
    }//GEN-LAST:event_btnCargarFotoActionPerformed
    public ArrayList<Departamento> dep;
    public ArrayList<Provincia> prov;
    public ArrayList<Distrito> dist;  
    private void comboDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDepartamentoActionPerformed
        comboProvincia.removeAllItems();
        if (comboDepartamento.getSelectedIndex() != -1) {
            for (int i = 0; i < prov.size(); i++) {
                if (dep.get(comboDepartamento.getSelectedIndex()).getCodDpto().equals(prov.get(i).getCodDpto())) {
                    comboProvincia.addItem(prov.get(i).getDesProv());
                }
            }
        }
    }//GEN-LAST:event_comboDepartamentoActionPerformed

    private void comboProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProvinciaActionPerformed
        comboDistrito.removeAllItems();
        if (comboDepartamento.getSelectedIndex() != -1 && comboProvincia.getSelectedIndex() != -1) {
            for (int i = 0; i < dist.size(); i++) {
                if (dep.get(comboDepartamento.getSelectedIndex()).getCodDpto().equals(dist.get(i).getCodDpto())
                        && prov.get(comboProvincia.getSelectedIndex()).getCodProv().equals(dist.get(i).getCodProv())) {
                    comboDistrito.addItem(dist.get(i).getDesDist());
                }
            }
        }
    }//GEN-LAST:event_comboProvinciaActionPerformed

    private void radioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioClienteActionPerformed
        if(radioCliente.isSelected()){
            radioBotonEspecialidad.setSelected(false);
            radioBotonProfesional.setSelected(false);
        }
    }//GEN-LAST:event_radioClienteActionPerformed

    private void radioBotonEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonEspecialidadActionPerformed
        if(radioBotonEspecialidad.isSelected()){
            radioCliente.setSelected(false);
            radioBotonProfesional.setSelected(false);
        }
    }//GEN-LAST:event_radioBotonEspecialidadActionPerformed

    private void radioBotonProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonProfesionalActionPerformed
        if(radioBotonProfesional.isSelected()){
            radioCliente.setSelected(false);
            radioBotonEspecialidad.setSelected(false);
        }
    }//GEN-LAST:event_radioBotonProfesionalActionPerformed
    boolean bandera=false;
    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        if(bandera==false){
            if (fecNac.getDate() != null && fecVigente.getDate() != null) {
                if (fecNac.getDate().compareTo(fecVigente.getDate()) > 0) {
                    JOptionPane.showMessageDialog(null, "La fecha de nacimiento debe ser menor. ");
                    bandera=true;
                }
            }
        }
    }//GEN-LAST:event_jPanel3MouseExited
    public ArrayList<Tics> auxiliarTics;
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
        OpcionesFrmPersona frame = new OpcionesFrmPersona();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void textDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDNIKeyTyped
        int numcaracteres=8;
        char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
      
      if(textDNI.getText().length()>=numcaracteres){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane, "DNI siempre es de 8 digitos");
          //textDNI.setText("");
      }
      
    }//GEN-LAST:event_textDNIKeyTyped

    private void comboTipoPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPersonaActionPerformed
        if(comboTipoPersona.getSelectedIndex()==0){
            comboCentroTrabajo.setEnabled(true);
            comboCargo.setEnabled(true);
        }
        else{
            comboCentroTrabajo.setEnabled(false);
            comboCargo.setEnabled(false);
        }
    }//GEN-LAST:event_comboTipoPersonaActionPerformed

    private void comboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCargoActionPerformed
        if(comboCargo.getSelectedIndex()==2){
            textCargo.setEnabled(true);
        }
        else{
            textCargo.setEnabled(false);
        }
    }//GEN-LAST:event_comboCargoActionPerformed

    private void comboLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLicenciaActionPerformed
        if(comboLicencia.getSelectedIndex()==0){
            comboVigencia.setEnabled(false);
        }
        else{
            comboVigencia.setEnabled(true);
        }
    }//GEN-LAST:event_comboLicenciaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    public String radioBotton(){
        if(radioCliente.isSelected()){
            return "1";
        }
        else{
            return "0";
        }
    }
    
    public String radioBotton2(){
        if(radioBotonEspecialidad.isSelected()){
            return "1";
        }
        else{
            return "0";
        }
    }
    
    public String radioBotton3(){
        if(radioBotonProfesional.isSelected()){
            return "1";
        }
        else{
            return "0";
        }
    }
    public ArrayList<Persona> personaJuridica;
    public void inicializarCombos(){
        DepartamentoDAO aux = new DepartamentoDAO();
        ProvinciaDAO aux2 = new ProvinciaDAO();
        DistritoDAO aux3 = new DistritoDAO();
        TicsDAO aux4 = new TicsDAO();
        PersonaDAO aux5 = new PersonaDAO();
        auxiliarTics = aux4.listTics();
        dep = aux.listDepartamento();
        prov = aux2.listProvincia();
        dist = aux3.listDistrito();
        personaJuridica = aux5.listPersonaJuridica();
        comboCentroTrabajo.removeAllItems();
        comboDepartamento.removeAllItems();
        comboProvincia.removeAllItems();
        comboDistrito.removeAllItems();
        for (int i = 0; i < dep.size(); i++) {
            comboDepartamento.addItem(dep.get(i).getDesDpto());
        }
        for (int i = 0; i < prov.size(); i++) {
            if (prov.get(i).getCodDpto().equals("001")) {
                comboProvincia.addItem(prov.get(i).getDesProv());
            }
        }
        for (int i = 0; i < dist.size(); i++) {
            if (dist.get(i).getCodProv().equals("001")) {
                comboDistrito.addItem(dist.get(i).getDesDist());
            }
        }
        for (int i = 0; i < personaJuridica.size(); i++) {
            comboCentroTrabajo.addItem(personaJuridica.get(i).getDesPersona());
        }
    }
    
    int posProv = -1;

    public String codProvincia() {
        String cod = new String();
        for (int i = 0; i < prov.size(); i++) {
            if (dep.get(comboDepartamento.getSelectedIndex()).getCodDpto().equals(prov.get(i).getCodDpto())
                    && prov.get(i).getDesProv().equals(String.valueOf(comboProvincia.getSelectedItem()))) {
                cod = prov.get(i).getCodProv();
                posProv = i;
            }
        }
        return cod;
    }
    public String codDistrito() {
        String cod = new String();
        for (int i = 0; i < dist.size(); i++) {
            if (dep.get(comboDepartamento.getSelectedIndex()).getCodDpto().equals(dist.get(i).getCodDpto())
                    && prov.get(posProv).getCodProv().equals(dist.get(i).getCodProv())
                    && dist.get(i).getDesDist().equals(String.valueOf(comboDistrito.getSelectedItem()))) {
                cod = dist.get(i).getCodDist();
            }
        }
        return cod;
    }

    public String devolverFecha(JDateChooser date){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        if (date.getDate() != null) {
            return formato.format(date.getDate());
        } else {
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAgregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAgregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAgregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAgregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAgregarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonVolver;
    private javax.swing.JButton btnCargarFoto;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JFileChooser cargarFotoMenu;
    public javax.swing.JComboBox<String> comboCargo;
    public javax.swing.JComboBox<String> comboCentroTrabajo;
    public javax.swing.JComboBox<String> comboDepartamento;
    public javax.swing.JComboBox<String> comboDistrito;
    public javax.swing.JComboBox<String> comboLicencia;
    public javax.swing.JComboBox<String> comboProvincia;
    public javax.swing.JComboBox<String> comboTipoPersona;
    public javax.swing.JComboBox<String> comboVigencia;
    public com.toedter.calendar.JDateChooser fecNac;
    public com.toedter.calendar.JDateChooser fecVigente;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jspObservaciones2;
    private javax.swing.JLabel label156116;
    private javax.swing.JLabel labelIconoMedios;
    private javax.swing.JLabel labelLicencia;
    private javax.swing.JLabel lblMostrarFoto;
    public javax.swing.JRadioButton radioBotonEspecialidad;
    public javax.swing.JRadioButton radioBotonProfesional;
    public javax.swing.JRadioButton radioCliente;
    public javax.swing.JTextField textCargo;
    public javax.swing.JTextField textDNI;
    public javax.swing.JTextArea textDescripcion;
    public javax.swing.JTextArea textDescripcion2;
    public javax.swing.JTextField textDireccion;
    public javax.swing.JTextArea textHobby;
    public javax.swing.JTextField textNROCIP;
    public javax.swing.JTextArea textObservaciones;
    // End of variables declaration//GEN-END:variables
}
