/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.Persona.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import edu.unmsm.sistemas.sgpy.Persona.menuPrincipales.OpcionesFrmCliente;
import edu.unmsm.sistemas.sgpy.Persona.menuPrincipales.OpcionesFrmMedioCom;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Persona;
import edu.unmsm.sistemas.sgpy.Persona.modelo.Tics;

/**
 *
 * @author Branco
 */
public class JFModificarMedioCom extends javax.swing.JFrame {

    /**
     * Creates new form JFPersonaTics
     */
    public JFModificarMedioCom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonaTics = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTicPersona = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodPersona = new javax.swing.JTextField();
        jTextFieldCodTic = new javax.swing.JTextField();
        VisualizarPersona = new javax.swing.JButton();
        VisualizarTic = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        ComboVigencia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        BotonModificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePersonaTics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "DNI", "Cargo"
            }
        ));
        jTablePersonaTics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonaTicsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonaTics);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 317, 94));

        jTableTicPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodTic", "Descripcion"
            }
        ));
        jTableTicPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTicPersonaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTicPersona);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 317, 93));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel1.setText("Código Persona:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 114, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel2.setText("Código Tic:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 174, -1, -1));
        jPanel1.add(jTextFieldCodPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 210, 26));
        jPanel1.add(jTextFieldCodTic, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 210, 26));

        VisualizarPersona.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        VisualizarPersona.setText("Visualizar Persona");
        jPanel1.add(VisualizarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        VisualizarTic.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        VisualizarTic.setText("Visualizar TIC");
        jPanel1.add(VisualizarTic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 140, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel3.setText("Descripción Medio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 233, -1, -1));
        jPanel1.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 210, 26));

        ComboVigencia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ComboVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Vigente", "Vigente" }));
        ComboVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboVigenciaActionPerformed(evt);
            }
        });
        jPanel1.add(ComboVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, 26));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel4.setText("Vigencia:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 292, -1, -1));

        BotonModificar.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        BotonModificar.setText("Modificar");
        jPanel1.add(BotonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel5.setText("Modificar Medio de Comunicación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean bandera2=false;
    public ArrayList<Persona> aux;
    public ArrayList<Tics> aux1;
    public DefaultTableModel modelo1;
    public DefaultTableModel modelo2;
    
    private void ComboVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboVigenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboVigenciaActionPerformed

    private void jTablePersonaTicsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonaTicsMouseClicked
        int fila = jTablePersonaTics.rowAtPoint(evt.getPoint());
        jTextFieldCodPersona.setEditable(true);
        jTextFieldCodPersona.setText(String.valueOf(aux.get(fila).getCodPers()));
    }//GEN-LAST:event_jTablePersonaTicsMouseClicked

    private void jTableTicPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTicPersonaMouseClicked
        int fila = jTableTicPersona.rowAtPoint(evt.getPoint());
        jTextFieldCodTic.setEditable(true);
        jTextFieldCodTic.setText(String.valueOf(aux1.get(fila).getCodTics()));
    }//GEN-LAST:event_jTableTicPersonaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        OpcionesFrmMedioCom frame = new OpcionesFrmMedioCom();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFModificarMedioCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFModificarMedioCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFModificarMedioCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFModificarMedioCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFModificarMedioCom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonModificar;
    public javax.swing.JComboBox<String> ComboVigencia;
    public javax.swing.JButton VisualizarPersona;
    public javax.swing.JButton VisualizarTic;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTablePersonaTics;
    public javax.swing.JTable jTableTicPersona;
    public javax.swing.JTextField jTextFieldCodPersona;
    public javax.swing.JTextField jTextFieldCodTic;
    public javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables
}
