package edu.unmsm.sistemas.sgpy.Proyecto.Vista;
import edu.unmsm.sistemas.sgpy.Proyecto.Logica.BackEnd;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Raul Emilio
 */
public class AgregarFrm extends javax.swing.JFrame {

    /**
     * Creates new form AgregarFrm
     */
    BackEnd Logica;
    DecimalFormat formateador=new DecimalFormat("#,###.##");
    DecimalFormatSymbols simbolo=new DecimalFormatSymbols();
    public AgregarFrm() {
        initComponents();
        setLocationRelativeTo(null);
        simbolo.setDecimalSeparator('.');
        simbolo.setGroupingSeparator(',');
        simbolo.setMonetaryDecimalSeparator('.');
        formateador.setDecimalFormatSymbols(simbolo);
        Logica= new BackEnd();
        try {T1.setText(String.valueOf(Logica.obtenerCodigoProyecto()));} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarFunciones();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarEstados();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarFases();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarDepartamentos();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarClientes();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarEspecialistas();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarResponsable();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        cajaNivel.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        T1 = new javax.swing.JTextField();
        cajaEstado = new javax.swing.JComboBox<>();
        T4 = new javax.swing.JTextField();
        cajaResponsable = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        dateBox1 = new datechooser.beans.DateChooserCombo();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCBDistrito = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jCBProvincia = new javax.swing.JComboBox<>();
        cajaCliente = new javax.swing.JComboBox<>();
        cajaFuncion = new javax.swing.JComboBox<>();
        cajaFase = new javax.swing.JComboBox<>();
        jCBDepartamento = new javax.swing.JComboBox<>();
        cajaEspecialista = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        cajaNivel = new javax.swing.JComboBox<>();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        labelTask2 = new org.edisoncor.gui.label.LabelTask();
        labelTask3 = new org.edisoncor.gui.label.LabelTask();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton1 = new org.edisoncor.gui.button.ButtonTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Proyecto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        T1.setEditable(false);
        T1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        T4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        T4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FormatoNumero(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarNumero(evt);
            }
        });

        cajaResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaResponsableActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Codigo");

        T5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        T5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FormatoNumero(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarNumero(evt);
            }
        });

        dateBox1.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateBox1.setCalendarPreferredSize(new java.awt.Dimension(400, 250));
    dateBox1.setNothingAllowed(false);
    dateBox1.setFormat(2);
    dateBox1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

    T2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    T2.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            IngresarNumero(evt);
        }
    });

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton2.setText("Anterior");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jCBProvincia.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCBProvinciaItemStateChanged(evt);
        }
    });

    cajaFuncion.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cajaFuncionActionPerformed(evt);
        }
    });

    cajaFase.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            cajaFaseItemStateChanged(evt);
        }
    });

    jCBDepartamento.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCBDepartamentoItemStateChanged(evt);
        }
    });
    jCBDepartamento.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCBDepartamentoActionPerformed(evt);
        }
    });

    cajaEspecialista.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cajaEspecialistaActionPerformed(evt);
        }
    });

    jCheckBox1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jCheckBox1.setSelected(true);
    jCheckBox1.setText("Vigente");

    cajaNivel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cajaNivelActionPerformed(evt);
        }
    });

    labelTask1.setText("DATOS DEL PROYECTO");
    labelTask1.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask1.setColorDeBorde(new java.awt.Color(0, 0, 0));
    labelTask1.setDescription(" ");

    labelTask2.setText("ZONA DE INFLUENCIA");
    labelTask2.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask2.setDescription(" ");

    labelTask3.setText("PERSONAL A CARGO");
    labelTask3.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask3.setDescription(" ");

    jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel12.setText("Fecha de registro");

    jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel20.setText("Fase");

    jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel21.setText("Costo PIP");

    jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel22.setText("Nivel");

    jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel23.setText("Funcion");

    jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel24.setText("Estado");

    jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel25.setText("Codigo SNIP");

    jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel26.setText("Nombre de proyecto");

    jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel27.setText("Costo DIR");

    jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel28.setText("Provincia");

    jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel29.setText("Departamento");

    jLabel30.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel30.setText("Distrito");

    jLabel31.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel31.setText("Cliente");

    jLabel32.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel32.setText("Especialista");

    jLabel33.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel33.setText("Responsable");

    jLabel34.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel34.setText("OBSERVACIONES");

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Imagenes/agregar.png"))); // NOI18N
    jButton1.setText("Guardar Proyecto");
    jButton1.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    jButton1.setDescription(" ");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelTask2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(231, 231, 231)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaFase, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(labelTask3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel28)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(jLabel30)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCBDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
        .addComponent(labelTask1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jCheckBox1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cajaResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(152, 152, 152))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(248, 248, 248)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)))))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(21, 21, 21)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel25))
            .addGap(7, 7, 7)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel26)
                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel12)
                .addComponent(dateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel20)
                .addComponent(cajaFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel22))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cajaNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel23)
                .addComponent(cajaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel24)
                .addComponent(cajaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addComponent(labelTask2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel29)
                .addComponent(jLabel28)
                .addComponent(jLabel30)
                .addComponent(jCBDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addComponent(labelTask3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel31))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cajaEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel32))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cajaResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel33))
            .addGap(18, 18, Short.MAX_VALUE)
            .addComponent(jLabel34)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jCheckBox1)
                    .addGap(76, 76, 76))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)))
            .addGap(52, 52, 52))
    );

    jScrollPane2.setViewportView(jPanel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBDepartamentoItemStateChanged
        jCBDistrito.removeAllItems();   //Borro la lista de distritos
        try {agregarProvincias();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        jCBProvincia.setSelectedIndex(-1);
    }//GEN-LAST:event_jCBDepartamentoItemStateChanged

    private void jCBProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBProvinciaItemStateChanged
        try {agregarDistritos();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        jCBDistrito.setSelectedIndex(-1);
    }//GEN-LAST:event_jCBProvinciaItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaMapaProyectos vmp = new VentanaMapaProyectos();
        vmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCBDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBDepartamentoActionPerformed

    private void cajaEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaEspecialistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaEspecialistaActionPerformed

    private void cajaNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNivelActionPerformed

    private void cajaFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaFuncionActionPerformed

    private void cajaResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaResponsableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codPyto=T1.getText();
        String codSNIP=T2.getText();
        String nombPyto=T3.getText();
        java.sql.Date fecReg=new java.sql.Date(dateBox1.getSelectedDate().getTimeInMillis());
        String costoPIP=T4.getText().replaceAll(",", "");
        String costoDIR=T5.getText().replaceAll(",", "");
        
        
        int codFuncion=cajaFuncion.getSelectedIndex()+1;                               //No puede ser Nulo
        int codEstado=cajaEstado.getSelectedIndex()+1;                                //No puede ser Nulo
        int codFase=cajaFase.getSelectedIndex()+1;
        int codNivel=cajaNivel.getSelectedIndex()+1;                                 //No puede ser Nulo
        codNivel=procesarFase(codNivel,codFase);                                //Obtiene el nivel respectivo
        
        //System.out.println("Cod. de Nivel, Funcion, Estado y Fase: "+codNivel+codFuncion+codEstado+codFase);
        String codDpto=ObtenerEntero3Cifras(jCBDepartamento.getSelectedIndex()+1);
        String codProv=ObtenerEntero3Cifras(jCBProvincia.getSelectedIndex()+1);
        String codDist=ObtenerEntero3Cifras(jCBDistrito.getSelectedIndex()+1);
        String nombCliente=String.valueOf(cajaCliente.getSelectedItem());   //No puede ser Nulo
        String nombEsp=String.valueOf(cajaEspecialista.getSelectedItem());       //No puede ser Nulo
        String nombResp=String.valueOf(cajaResponsable.getSelectedItem());       //No puede ser Nulo
        String Observac=jTextArea1.getText().replaceAll("\n", " ");
        Observac= (Observac.equals(""))?" ":Observac;
        String Vigente=(jCheckBox1.isSelected())?"1":"0";
        if(!nombPyto.equals("") && !costoPIP.equals("") && !costoDIR.equals("") && !codDpto.equals("000") && !codProv.equals("000") && !codDist.equals("000"))
            if(comprobarDouble(costoPIP) || comprobarDouble(costoDIR)){
                
            try {Logica.guardarProyecto(codPyto,codFase,codNivel,codSNIP, nombPyto, fecReg, Double.parseDouble(costoPIP), Double.parseDouble(costoDIR), codEstado, ObtenerEntero4Cifras(codFuncion), codDpto, codProv, codDist, nombCliente, nombEsp, nombResp,Observac, Vigente);
                this.dispose();
                new OpcionesFrm().setVisible(true);
            } 
            catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
            
                
            }
            else
                JOptionPane.showMessageDialog(this, "Los Costos de PIP y DIR no son adecuados");
        else
            JOptionPane.showMessageDialog(this, "Le falta llenar algun campo.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cajaFaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cajaFaseItemStateChanged
        try {agregarNiveles(cajaFase.getSelectedIndex()+1);} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_cajaFaseItemStateChanged

    private void FormatoNumero(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FormatoNumero
        char entrada=evt.getKeyChar();
        
        javax.swing.JTextField aux=(javax.swing.JTextField)evt.getComponent();
        
        if(Character.isDigit(entrada) || entrada=='.'){
            String txt=aux.getText();
            if(entrada!='.'){
                txt=txt.replaceAll(",", "");
                double valor=Double.parseDouble(txt);
                aux.setText(formateador.format(valor));
            } 
        }
        else{
            evt.consume();
        }
    }//GEN-LAST:event_FormatoNumero

    private void IngresarNumero(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarNumero
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.')
            evt.consume();
    }//GEN-LAST:event_IngresarNumero

    //Funciones de Comprobación
    private boolean comprobarDouble(String numero){
        try{
            Double.parseDouble(numero);
            return true;
        }catch(Exception e){
            return false;
        }
    }
    private String ObtenerEntero3Cifras(int numero){
        int tam= Integer.toString(numero).length();
        switch (tam){
            case 1: return "00"+Integer.toString(numero);
            case 2: return "0"+Integer.toString(numero);
            case 3: return Integer.toString(numero);
        }
        return null;
    }
    private String ObtenerEntero4Cifras(int numero){
        int tam= Integer.toString(numero).length();
        switch (tam){
            case 1: return "000"+Integer.toString(numero);
            case 2: return "00"+Integer.toString(numero);
            case 3: return "0"+Integer.toString(numero);
            case 4: return Integer.toString(numero);
        }
        return null;
    }
    private int procesarFase(int codnivel,int codfase){
        switch(codfase){
            case 1:             //Fase preinversion tiene niveles 1 y 2
                return codnivel;
            case 2:
                return codnivel+2;    //Fase inversion tiene niveles 3 y 4
            case 3:
                return codnivel+4;    //Fase posinversion tiene niveles 5 y 6
            default:
                return -1;
        }
    }
    
    
    //Funciones para agregar datos
    private void agregarNiveles(int codfase) throws SQLException{
        cajaNivel.removeAllItems();
        String[] Nivel=Logica.leerNiveles(codfase).split("#"); //Deben existir al menos 1 nivel
        int tam=Nivel.length;
        
        for(int i=0;i<tam;i++)
            cajaNivel.addItem((i+1)+".- "+Nivel[i]);
    }
    private void agregarFunciones() throws SQLException{
        String[] Funcion=Logica.leerFunciones().split("#"); //Deben existir al menos 1 funcion
        int tam=Funcion.length;
        for(int i=0;i<tam;i++)
            cajaFuncion.addItem((i+1)+".- "+Funcion[i]);
        cajaFuncion.setSelectedIndex(-1);
    }
    private void agregarEstados() throws SQLException{
        String[] Estado=Logica.leerEstados().split("#"); //Deben existir al menos 1 estado
        int tam=Estado.length;
        for(int i=0;i<tam;i++)
            cajaEstado.addItem((i+1)+".- "+Estado[i]);
        cajaEstado.setSelectedIndex(-1);
    }
    
    private void agregarFases() throws SQLException{
        String[] Estado=Logica.leerFases().split("#"); //Deben existir al menos 1 estado
        int tam=Estado.length;
        for(int i=0;i<tam;i++)
            cajaFase.addItem((i+1)+".- "+Estado[i]);
        cajaFase.setSelectedIndex(-1);
    }
    private void agregarDepartamentos() throws SQLException{
        String[] Departamento=Logica.leerDepartamentos().split("#"); //Deben existir al menos 1 departamento
        int tam=Departamento.length;
        for(int i=0;i<tam;i++)
            jCBDepartamento.addItem(Departamento[i]);
        jCBDepartamento.setSelectedIndex(-1);
    }
    private void agregarProvincias() throws SQLException{
        String[] Provincia=Logica.leerProvincias(String.valueOf(jCBDepartamento.getSelectedItem())).split("#"); //Deben existir al menos 1 provincia
        int tam=Provincia.length;
        jCBProvincia.removeAllItems();
        for(int i=0;i<tam;i++)
            jCBProvincia.addItem(Provincia[i]);
    }
    private void agregarDistritos() throws SQLException{
        String[] Distrito=Logica.leerDistritos(String.valueOf(jCBProvincia.getSelectedItem()),String.valueOf(jCBDepartamento.getSelectedItem())).split("#"); //Deben existir al menos 1 distrito
        int tam=Distrito.length;
        jCBDistrito.removeAllItems();
        for(int i=0;i<tam;i++)
            jCBDistrito.addItem(Distrito[i]);
    }
    private void agregarClientes() throws SQLException{
        String[] Cliente=Logica.leerClientes().split("#"); //Deben existir al menos 1 nivel
        int tam=Cliente.length;
        for(int i=0;i<tam;i++)
            cajaCliente.addItem(Cliente[i]);
        cajaCliente.setSelectedIndex(-1);
    }
    private void agregarEspecialistas() throws SQLException{
        String[] Especialista=Logica.leerEspecialistas().split("#"); //Deben existir al menos 1 nivel
        int tam=Especialista.length;
        for(int i=0;i<tam;i++)
            cajaEspecialista.addItem(Especialista[i]);
        cajaEspecialista.setSelectedIndex(-1);
    }
    private void agregarResponsable() throws SQLException{
        String[] Responsable=Logica.leerEspecialistas().split("#"); //Deben existir al menos 1 nivel
        int tam=Responsable.length;
        for(int i=0;i<tam;i++)
            cajaResponsable.addItem(Responsable[i]);
        cajaResponsable.setSelectedIndex(-1);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JComboBox<String> cajaCliente;
    private javax.swing.JComboBox<String> cajaEspecialista;
    private javax.swing.JComboBox<String> cajaEstado;
    private javax.swing.JComboBox<String> cajaFase;
    private javax.swing.JComboBox<String> cajaFuncion;
    private javax.swing.JComboBox<String> cajaNivel;
    private javax.swing.JComboBox<String> cajaResponsable;
    private datechooser.beans.DateChooserCombo dateBox1;
    private org.edisoncor.gui.button.ButtonTask jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBDepartamento;
    private javax.swing.JComboBox<String> jCBDistrito;
    private javax.swing.JComboBox<String> jCBProvincia;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.label.LabelTask labelTask2;
    private org.edisoncor.gui.label.LabelTask labelTask3;
    // End of variables declaration//GEN-END:variables
}
