package edu.unmsm.sistemas.sgpy.Proyecto.Vista;
import edu.unmsm.sistemas.sgpy.Proyecto.Logica.BackEnd;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Raul Emilio
 */
public class BorrarFrm extends javax.swing.JFrame {

    /**
     * Creates new form AgregarFrm
     */
    BackEnd Logica;
    String codPyto="";
    DecimalFormat formateador=new DecimalFormat("#,###.##");
    DecimalFormatSymbols simbolo=new DecimalFormatSymbols();
    
    public BorrarFrm(String codPyto) {
        initComponents();
        setLocationRelativeTo(null);
        simbolo.setDecimalSeparator('.');
        simbolo.setGroupingSeparator(',');
        simbolo.setMonetaryDecimalSeparator('.');
        formateador.setDecimalFormatSymbols(simbolo);
        Logica= new BackEnd();
        try {Logica.desactivarAutoCommit();} 
        catch (SQLException ex) {Logger.getLogger(BorrarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        this.codPyto=codPyto;
        
        try {agregarFases();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarFunciones();} 
        catch (SQLException ex) {Logger.getLogger(VisualizarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarEstados(cajaEstado);} 
        catch (SQLException ex) {Logger.getLogger(VisualizarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarDepartamentos();} 
        catch (SQLException ex) {Logger.getLogger(VisualizarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarClientes();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarEspecialistas();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}

        try {agregarResponsable();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {recuperarDatos();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jCBDistrito = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaFase = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cajaResponsable = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dateBox1 = new datechooser.beans.DateChooserCombo();
        T5 = new javax.swing.JTextField();
        cajaNivel = new javax.swing.JComboBox<>();
        cajaFuncion = new javax.swing.JComboBox<>();
        cajaEstado = new javax.swing.JComboBox<>();
        jCBDepartamento = new javax.swing.JComboBox<>();
        cajaCliente = new javax.swing.JComboBox<>();
        cajaEspecialista = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBProvincia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        labelTask2 = new org.edisoncor.gui.label.LabelTask();
        labelTask3 = new org.edisoncor.gui.label.LabelTask();
        jButton3 = new org.edisoncor.gui.button.ButtonTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cancelar Proyecto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setText("Distrito:");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("Costo PIP:");

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel16.setText("Fase:");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Nivel:");

        cajaFase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cajaFaseItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("Funcion:");

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setText("Responsable:");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("Estado:");

        cajaResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaResponsableActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Departamento:");

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel17.setText("OBSERVACIONES");

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("Cliente:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("Especialista:");

        T1.setEditable(false);
        T1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel18.setText("Codigo SNIP:");

        T3.setEditable(false);

        T4.setEditable(false);
        T4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        T2.setEditable(false);
        T2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel19.setText("Costo DIR:");

        dateBox1.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateBox1.setCalendarPreferredSize(new java.awt.Dimension(400, 250));
    dateBox1.setNothingAllowed(false);
    dateBox1.setFormat(2);
    dateBox1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

    T5.setEditable(false);
    T5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jCBDepartamento.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCBDepartamentoItemStateChanged(evt);
        }
    });

    jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jButton1.setText("Salir");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel13.setText("Provincia");

    jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel2.setText("Codigo:");

    jCBProvincia.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCBProvinciaItemStateChanged(evt);
        }
    });

    jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel3.setText("Nombre del Proyecto:");

    jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel4.setText("Fecha de Registro:");

    labelTask1.setText("DATOS DEL PROYECTO");
    labelTask1.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask1.setColorDeBorde(new java.awt.Color(0, 0, 0));
    labelTask1.setDescription(" ");

    labelTask2.setText("ZONA DE INFLUENCIA");
    labelTask2.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask2.setDescription(" ");

    labelTask3.setText("PERSONAL A CARGO");
    labelTask3.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask3.setDescription(" ");

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Imagenes/Cancelar.png"))); // NOI18N
    jButton3.setText("Cancelar Proyecto");
    jButton3.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    jButton3.setDescription(" ");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(labelTask3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelTask2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelTask1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(102, 102, 102)
            .addComponent(jLabel9)
            .addGap(4, 4, 4)
            .addComponent(jCBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel13)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel14)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jCBDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jButton1)
                    .addGap(165, 165, 165)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel17)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(103, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cajaCliente, 0, 327, Short.MAX_VALUE)
                                .addComponent(cajaEspecialista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cajaResponsable, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel15))
                    .addGap(164, 164, 164))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(jLabel16))
                            .addGap(63, 63, 63)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cajaNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cajaFuncion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cajaEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cajaFase, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(81, 81, 81)
                            .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(84, 84, 84))))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel18)
                .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(dateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel19)
                .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16)
                .addComponent(cajaFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(2, 2, 2)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(cajaNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(cajaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(cajaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addComponent(labelTask2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jCBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13)
                .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel14)
                .addComponent(jCBDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addComponent(labelTask3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(cajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(cajaEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel15)
                .addComponent(cajaResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(24, 24, 24)
            .addComponent(jLabel17)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(11, 11, 11)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    jScrollPane1.setViewportView(jPanel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBProvinciaItemStateChanged
        try {agregarDistritos();}
        catch (SQLException ex) {Logger.getLogger(BorrarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        jCBDistrito.setSelectedIndex(-1);
    }//GEN-LAST:event_jCBProvinciaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Logica.borrarProyecto(codPyto);
        //new BuscarFrm('b').setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCBDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBDepartamentoItemStateChanged
        jCBDistrito.removeAllItems();   //Borro la lista de distritos
        try {agregarProvincias();}
        catch (SQLException ex) {Logger.getLogger(BorrarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        jCBProvincia.setSelectedIndex(-1);
    }//GEN-LAST:event_jCBDepartamentoItemStateChanged

    private void cajaResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaResponsableActionPerformed

    private void cajaFaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cajaFaseItemStateChanged
        try {agregarNiveles(cajaFase.getSelectedIndex()+1);}
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_cajaFaseItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Logica.borrarProyecto(codPyto);
            Logica.Commit();
        } catch (SQLException ex) {
            Logger.getLogger(BorrarFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        //new BuscarFrm('e').setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    //Funciones de Comprobación
    private boolean comprobarDouble(String numero){
        try{
            Double.parseDouble(numero);
            return true;
        }catch(Exception e){
            return false;
        }
    }
    private String ObtenerEntero3Cifras(int numero){
        int tam= Integer.toString(numero).length();
        switch (tam){
            case 1: return "00"+Integer.toString(numero);
            case 2: return "0"+Integer.toString(numero);
            case 3: return Integer.toString(numero);
        }
        return null;
    }
    private String ObtenerEntero4Cifras(int numero){
        int tam= Integer.toString(numero).length();
        switch (tam){
            case 1: return "000"+Integer.toString(numero);
            case 2: return "00"+Integer.toString(numero);
            case 3: return "0"+Integer.toString(numero);
            case 4: return Integer.toString(numero);
        }
        return null;
    }
    private int procesarFase(int codnivel,int codfase){
        switch(codfase){
            case 1:             //Fase preinversion tiene niveles 1 y 2
                return codnivel-4;
            case 2:
                return codnivel-2;    //Fase inversion tiene niveles 3 y 4
            case 3:
                return codnivel;    //Fase posinversion tiene niveles 5 y 6
            default:
                return -1;
        }
    }
    
    //Funciones para agregar datos
    private void agregarNiveles(int codfase) throws SQLException{
        cajaNivel.removeAllItems();
        String[] Nivel=Logica.leerNiveles(codfase).split("#"); //Deben existir al menos 1 nivel
        int tam=Nivel.length;
        
        for(int i=0;i<tam;i++)
            cajaNivel.addItem(Nivel[i]);
    }
    
    private void agregarFunciones() throws SQLException{
        String[] Funcion=Logica.leerFunciones().split("#"); //Deben existir al menos 1 funcion
        int tam=Funcion.length;
        for(int i=0;i<tam;i++)
            cajaFuncion.addItem(Funcion[i]);
    }
    private void agregarEstados(JComboBox caja) throws SQLException{
        String[] Estado=Logica.leerEstados().split("#"); //Deben existir al menos 1 estado
        int tam=Estado.length;
        for(int i=0;i<tam;i++)
            caja.addItem(Estado[i]);
    }
    private void agregarFases() throws SQLException{
        String[] Estado=Logica.leerFases().split("#"); //Deben existir al menos 1 estado
        int tam=Estado.length;
        for(int i=0;i<tam;i++)
            cajaFase.addItem(Estado[i]);
        
    }
    private void agregarDepartamentos() throws SQLException{
        String[] Departamento=Logica.leerDepartamentos().split("#"); //Deben existir al menos 1 departamento
        int tam=Departamento.length;
        for(int i=0;i<tam;i++)
            jCBDepartamento.addItem(Departamento[i]);
        jCBDepartamento.setSelectedIndex(-1);
    }
    private void agregarProvincias() throws SQLException{
        String[] Provincia=Logica.leerProvincias(String.valueOf(jCBDepartamento.getSelectedItem())).split("#"); //Deben existir al menos 1 provincia
        int tam=Provincia.length;
        jCBProvincia.removeAllItems();
        for(int i=0;i<tam;i++)
            jCBProvincia.addItem(Provincia[i]);
    }
    private void agregarDistritos() throws SQLException{
        String[] Distrito=Logica.leerDistritos(String.valueOf(jCBProvincia.getSelectedItem()),String.valueOf(jCBDepartamento.getSelectedItem())).split("#"); //Deben existir al menos 1 distrito
        int tam=Distrito.length;
        jCBDistrito.removeAllItems();
        for(int i=0;i<tam;i++)
            jCBDistrito.addItem(Distrito[i]);
    }
    private void agregarClientes() throws SQLException{
        String[] Cliente=Logica.leerClientes().split("#"); //Deben existir al menos 1 nivel
        int tam=Cliente.length;
        for(int i=0;i<tam;i++)
            cajaCliente.addItem(Cliente[i]);
    }
    private void agregarEspecialistas() throws SQLException{
        String[] Especialista=Logica.leerEspecialistas().split("#"); //Deben existir al menos 1 nivel
        int tam=Especialista.length;
        for(int i=0;i<tam;i++)
            cajaEspecialista.addItem(Especialista[i]);
    }
    private void agregarResponsable() throws SQLException{
        String[] Responsable=Logica.leerEspecialistas().split("#"); //Deben existir al menos 1 nivel
        int tam=Responsable.length;
        for(int i=0;i<tam;i++)
            cajaResponsable.addItem(Responsable[i]);
    }
    
    //Funcion de Recuperacion de la Base de Datos
    private void recuperarDatos() throws SQLException{
        Object[] datos=Logica.recuperarProyecto(codPyto);
        T1.setText(String.valueOf(datos[0]));   //CodPyto
        cajaFase.setSelectedItem(String.valueOf(datos[1]));   //nombFase
        agregarNiveles(cajaFase.getSelectedIndex()+1);
        cajaNivel.setSelectedItem(String.valueOf(datos[2]));    //nombNivel
        T2.setText(String.valueOf(datos[3])); //codSNIP
        T3.setText(String.valueOf(datos[4]));   //NomPyto
        Calendar Cal = new GregorianCalendar();Cal.setTimeInMillis(Long.parseLong(String.valueOf(datos[5])));
        dateBox1.setCurrent(Cal);           //FecReg
        dateBox1.setText(Cal.get(Calendar.DAY_OF_MONTH)+"/"+(Cal.get(Calendar.MONTH)+1)+"/"+Cal.get(Calendar.YEAR));
        dateBox1.setEnabled(false);
        T4.setText(formateador.format(Double.parseDouble(String.valueOf(datos[6]))));   //Costo PIP
        T5.setText(formateador.format(Double.parseDouble(String.valueOf(datos[7]))));   //Costo DIR
        cajaEstado.setSelectedItem((String.valueOf(datos[8])));    //EstPyto
        cajaFuncion.setSelectedItem((String.valueOf(datos[9])));    //CodFuncion
        jCBDepartamento.setSelectedItem((String.valueOf(datos[10])));    //codDepartamento
        jCBProvincia.setSelectedItem((String.valueOf(datos[11])));    //codProvincia
        jCBDistrito.setSelectedItem((String.valueOf(datos[12])));     //codDistrito
        cajaCliente.setSelectedItem(datos[13]);            //codCliente
        cajaEspecialista.setSelectedItem(datos[14]);            //codEspecialista
        cajaResponsable.setSelectedItem(datos[15]);           //codResponsable
        jTextArea1.setText(datos[16].toString());   //Observación
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JComboBox<String> cajaCliente;
    private javax.swing.JComboBox<String> cajaEspecialista;
    private javax.swing.JComboBox<String> cajaEstado;
    private javax.swing.JComboBox<String> cajaFase;
    private javax.swing.JComboBox<String> cajaFuncion;
    private javax.swing.JComboBox<String> cajaNivel;
    private javax.swing.JComboBox<String> cajaResponsable;
    private datechooser.beans.DateChooserCombo dateBox1;
    private javax.swing.JButton jButton1;
    private org.edisoncor.gui.button.ButtonTask jButton3;
    private javax.swing.JComboBox<String> jCBDepartamento;
    private javax.swing.JComboBox<String> jCBDistrito;
    private javax.swing.JComboBox<String> jCBProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.label.LabelTask labelTask2;
    private org.edisoncor.gui.label.LabelTask labelTask3;
    // End of variables declaration//GEN-END:variables
}
