/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.Proyecto.Vista;

import edu.unmsm.sistemas.sgpy.Proyecto.Logica.BackEnd;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raul Emilio
 */
public class BuscarFrm extends javax.swing.JFrame {

    /**
     * Creates new form BuscarFrm
     */
    char Tipo;
    DefaultTableModel modelo=new DefaultTableModel(){@Override public boolean isCellEditable(int row, int column){return false;}};
    BackEnd backend= new BackEnd();
    DecimalFormat formateador=new DecimalFormat("#,###.##");
    DecimalFormatSymbols simbolo=new DecimalFormatSymbols();
    
    public BuscarFrm(char Tipo) {
        initComponents();
        setLocationRelativeTo(null);
        simbolo.setDecimalSeparator('.');
        simbolo.setGroupingSeparator(',');
        simbolo.setMonetaryDecimalSeparator('.');
        formateador.setDecimalFormatSymbols(simbolo);
        this.Tipo=Tipo;
        switch(Tipo){
            case 'e':
                E1.setText("Cancelar Proyecto");
                break;
            case 'm':
                E1.setText("Modificar Proyecto");
                break;
            case 'v':
                E1.setText("Visualizar Proyecto");
                break;
        }
        jTable1.setModel(modelo);
        
        String[] columnas={"Codigo","Nombre ","Fech. de Reg.", "Costo PIP", "Costo Dir."}; 
        modelo.setColumnIdentifiers(columnas);
        
        jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(0).setMinWidth(80);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(300);
        jTable1.getColumnModel().getColumn(1).setMinWidth(300);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(2).setMinWidth(100);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        E1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        E3 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        E2 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        buttonTask1 = new org.edisoncor.gui.button.ButtonTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        E1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        E1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E1.setText("Buscar Proyecto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(E1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(E1)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        E3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        E3.setText("Nombre");

        T2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        T2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                T2KeyPressed(evt);
            }
        });

        jButton1.setText("Buscar por Código");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar por Nombre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        E2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        E2.setText("Codigo");

        T1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        T1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                T1KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre Proyecto", "Fecha Registro", "Costo PIP", "Costo DIR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonTask1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Imagenes/buscar2.png"))); // NOI18N
        buttonTask1.setText("Ingresar");
        buttonTask1.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        buttonTask1.setDescription(" ");
        buttonTask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTask1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(E3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(186, 186, 186))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton3)
                .addGap(321, 321, 321)
                .addComponent(buttonTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(E2))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E3)
                    .addComponent(jButton2))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Buscar Proyecto según código
        String codPyto=T1.getText();
        if(!codPyto.equals("")){
            boolean existe=backend.verificarExistenciaProyecto(codPyto);
            modelo.setRowCount(0);  //Limpia la tabla
            if(existe){
                if(Tipo!='m'){  //Si se va a agregar o cancelar
                    try {
                        Object[] Proyecto= backend.buscarProyecto(codPyto);
                        Calendar Cal = new GregorianCalendar();Cal.setTimeInMillis(Long.parseLong(String.valueOf(Proyecto[2])));
                        Proyecto[2]=Cal.get(Calendar.DAY_OF_MONTH)+"/"+(Cal.get(Calendar.MONTH)+1)+"/"+Cal.get(Calendar.YEAR);
                        Proyecto[3]=formateador.format(Double.parseDouble(String.valueOf(Proyecto[3].toString())));
                        Proyecto[4]=formateador.format(Double.parseDouble(String.valueOf(Proyecto[4].toString())));
                        modelo.setRowCount(0);  //Limpia la tabla
                        modelo.addRow(Proyecto);
                    } catch (SQLException ex) {
                        Logger.getLogger(BuscarFrm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else{   //Si se va a modificar
                    try {
                        Object[] Proyecto= backend.buscarProyectoModificar(codPyto);
                        Calendar Cal = new GregorianCalendar();Cal.setTimeInMillis(Long.parseLong(String.valueOf(Proyecto[2])));
                        Proyecto[2]=Cal.get(Calendar.DAY_OF_MONTH)+"/"+(Cal.get(Calendar.MONTH)+1)+"/"+Cal.get(Calendar.YEAR);
                        Proyecto[3]=formateador.format(Double.parseDouble(String.valueOf(Proyecto[3].toString())));
                        Proyecto[4]=formateador.format(Double.parseDouble(String.valueOf(Proyecto[4].toString())));
                        modelo.setRowCount(0);  //Limpia la tabla
                        modelo.addRow(Proyecto);
                    } catch (SQLException ex) {
                        Logger.getLogger(BuscarFrm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            else{
                //No existe el Proyecto
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Buscar Proyecto según nombre
        String nombrePyto=T2.getText();
        try {
            if(Tipo!='m'){  //Si se va a agregar o cancelar
                String Proyectos= backend.buscarProyectoNombre(nombrePyto);
                modelo.setRowCount(0);  //Limpia la tabla
                if(!Proyectos.equals("")){
                    String[] Proyecto=Proyectos.split("-");
                    int tam=Proyecto.length;
                    for(int i=0;i<tam;i++){
                        String[] aux=Proyecto[i].split("#");
                        Calendar Cal = new GregorianCalendar();Cal.setTimeInMillis(Long.parseLong(String.valueOf(aux[2])));
                        aux[2]=Cal.get(Calendar.DAY_OF_MONTH)+"/"+(Cal.get(Calendar.MONTH)+1)+"/"+Cal.get(Calendar.YEAR);
                        //System.out.println(aux);
                        aux[3]=formateador.format(Double.parseDouble(String.valueOf(aux[3].toString())));
                        aux[4]=formateador.format(Double.parseDouble(String.valueOf(aux[4].toString())));
                        modelo.addRow(aux);
                    }
                }
                else{
                    //No hay ningun proyecto con ese nombre
                }
            }
            else{   //Si se va a modificar
                String Proyectos= backend.buscarProyectoNombreModificar(nombrePyto);
                modelo.setRowCount(0);  //Limpia la tabla
                if(!Proyectos.equals("")){
                    String[] Proyecto=Proyectos.split("-");
                    int tam=Proyecto.length;
                    for(int i=0;i<tam;i++){
                        String[] aux=Proyecto[i].split("#");
                        Calendar Cal = new GregorianCalendar();Cal.setTimeInMillis(Long.parseLong(String.valueOf(aux[2])));
                        aux[2]=Cal.get(Calendar.DAY_OF_MONTH)+"/"+(Cal.get(Calendar.MONTH)+1)+"/"+Cal.get(Calendar.YEAR);
                        //System.out.println(aux);
                        aux[3]=formateador.format(Double.parseDouble(String.valueOf(aux[3].toString())));
                        aux[4]=formateador.format(Double.parseDouble(String.valueOf(aux[4].toString())));
                        modelo.addRow(aux);
                    }
                }
                else{
                    //No hay ningun proyecto con ese nombre
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(BuscarFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new OpcionesFrm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void T1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1.doClick();
        }
    }//GEN-LAST:event_T1KeyPressed

    private void T2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton2.doClick();
        }
    }//GEN-LAST:event_T2KeyPressed

    private void buttonTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTask1ActionPerformed
      int filaSeleccionada=jTable1.getSelectedRow();
        if(filaSeleccionada>=0){
            String codPyto=String.valueOf(modelo.getValueAt(filaSeleccionada, 0));
            switch (Tipo) {
                //Eliminar
                    case 'e':
                        new BorrarFrm(codPyto).setVisible(true); //Abrir ventana de Modificar con el codPyto
                        //this.dispose();
                        break;
                //Modificar
                    case 'm':
                        new ModificarFrm(codPyto).setVisible(true); //Abrir ventana de Modificar con el codPyto
                        //this.dispose();
                        break;
                //Visualizar
                    case 'v':
                        new VisualizarFrm(codPyto).setVisible(true); //Abrir ventana de Visualizar con el codPyto
                        //this.dispose();
                        break;
                    default:
                        break;
            }
        }

    }//GEN-LAST:event_buttonTask1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private org.edisoncor.gui.button.ButtonTask buttonTask1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
