package edu.unmsm.sistemas.sgpy.Proyecto.Vista;
import edu.unmsm.sistemas.sgpy.Proyecto.Logica.BackEnd;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Raul Emilio
 */
public class ModificarFrm extends javax.swing.JFrame {

    /**
     * Creates new form AgregarFrm
     */
    BackEnd Logica;
    String codPyto="";
    DecimalFormat formateador=new DecimalFormat("#,###.##");
    DecimalFormatSymbols simbolo=new DecimalFormatSymbols();
    
    public ModificarFrm(String codPyto) {
        initComponents();
        setLocationRelativeTo(null);
        simbolo.setDecimalSeparator('.');
        simbolo.setGroupingSeparator(',');
        simbolo.setMonetaryDecimalSeparator('.');
        formateador.setDecimalFormatSymbols(simbolo);
        Logica= new BackEnd();
        try {Logica.desactivarAutoCommit();} 
        catch (SQLException ex) {Logger.getLogger(VisualizarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        this.codPyto=codPyto;
        
        try {agregarFases();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarFunciones();} 
        catch (SQLException ex) {Logger.getLogger(VisualizarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarEstados(cajaEstado);} 
        catch (SQLException ex) {Logger.getLogger(VisualizarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        
        
        try {agregarDepartamentos();} 
        catch (SQLException ex) {Logger.getLogger(VisualizarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarClientes();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {agregarEspecialistas();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}

        try {agregarResponsable();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        
        try {recuperarDatos();} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateBox1 = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cajaEstado = new javax.swing.JComboBox<>();
        cajaFuncion = new javax.swing.JComboBox<>();
        cajaNivel = new javax.swing.JComboBox<>();
        cajaFase = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jCBDepartamento = new javax.swing.JComboBox<>();
        jCBProvincia = new javax.swing.JComboBox<>();
        jCBDistrito = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cajaCliente = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cajaEspecialista = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cajaResponsable = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        labelTask2 = new org.edisoncor.gui.label.LabelTask();
        labelTask3 = new org.edisoncor.gui.label.LabelTask();
        jButton3 = new org.edisoncor.gui.button.ButtonTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Proyecto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Codigo");

        T1.setEditable(false);
        T1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel35.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel35.setText("Codigo SNIP");

        T2.setEditable(false);
        T2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarNumero(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del Proyecto");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("Fecha de Registro");

        dateBox1.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateBox1.setCalendarPreferredSize(new java.awt.Dimension(400, 250));
    dateBox1.setNothingAllowed(false);
    dateBox1.setFormat(2);
    dateBox1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

    jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel5.setText("Costo PIP");

    T4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    T4.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            FormatoNumero(evt);
        }
    });

    T5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    T5.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            FormatoNumero(evt);
        }
    });

    jLabel32.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel32.setText("Fase");

    jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel6.setText("Nivel");

    jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel7.setText("Funcion");

    jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel8.setText("Estado");

    cajaFase.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            cajaFaseItemStateChanged(evt);
        }
    });

    jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel9.setText("Departamento");

    jCBDepartamento.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCBDepartamentoItemStateChanged(evt);
        }
    });

    jCBProvincia.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCBProvinciaItemStateChanged(evt);
        }
    });

    jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel14.setText("Distrito");

    jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel13.setText("Provincia");

    jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel10.setText("Cliente");

    jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel11.setText("Especialista");

    jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel15.setText("Responsable");

    cajaResponsable.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cajaResponsableActionPerformed(evt);
        }
    });

    jLabel33.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel33.setText("OBSERVACIONES");

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane3.setViewportView(jTextArea1);

    jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
    jCheckBox1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jCheckBox1.setText("Vigente");

    jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jButton2.setText("Anterior");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jLabel34.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
    jLabel34.setText("Costo DIR");

    labelTask1.setText("DATOS DEL PROYECTO");
    labelTask1.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask1.setColorDeBorde(new java.awt.Color(0, 0, 0));
    labelTask1.setDescription(" ");

    labelTask2.setText("ZONA DE INFLUENCIA");
    labelTask2.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask2.setDescription(" ");

    labelTask3.setText("PERSONAL A CARGO");
    labelTask3.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    labelTask3.setDescription(" ");

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/Imagenes/modificar.png"))); // NOI18N
    jButton3.setText("Actualizar Proyecto");
    jButton3.setCategoryFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    jButton3.setDescription(" ");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cajaResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cajaEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(76, 76, 76)
                                    .addComponent(cajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(106, 106, 106))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel32))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(63, 63, 63)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cajaNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cajaFuncion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cajaEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cajaFase, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jCBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCBDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                            .addComponent(jLabel35)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(T3)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(T4)
                                                .addComponent(dateBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                            .addGap(39, 39, 39)
                                            .addComponent(jLabel34)
                                            .addGap(18, 18, 18)
                                            .addComponent(T5)))))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelTask3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(labelTask1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(labelTask2, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jButton2)
                            .addGap(146, 146, 146)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox1)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel33)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(17, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(21, 21, 21)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel35)
                .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(dateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel34)
                    .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel32)
                .addComponent(cajaFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(cajaNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(cajaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(cajaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addComponent(labelTask2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jCBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13)
                .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel14)
                .addComponent(jCBDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addComponent(labelTask3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(cajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel10)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cajaEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cajaResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel15))
            .addGap(24, 24, 24)
            .addComponent(jLabel33)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jCheckBox1)
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2))
            .addGap(0, 0, Short.MAX_VALUE))
    );

    jScrollPane1.setViewportView(jPanel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBDepartamentoItemStateChanged
        jCBDistrito.removeAllItems();   //Borro la lista de distritos
        try {agregarProvincias();} 
        catch (SQLException ex) {Logger.getLogger(ModificarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        jCBProvincia.setSelectedIndex(-1);
    }//GEN-LAST:event_jCBDepartamentoItemStateChanged

    private void jCBProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBProvinciaItemStateChanged
        try {agregarDistritos();} 
        catch (SQLException ex) {Logger.getLogger(ModificarFrm.class.getName()).log(Level.SEVERE, null, ex);}
        jCBDistrito.setSelectedIndex(-1);
    }//GEN-LAST:event_jCBProvinciaItemStateChanged

    private void cajaResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaResponsableActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //new BuscarFrm('m').setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cajaFaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cajaFaseItemStateChanged
        try {agregarNiveles(cajaFase.getSelectedIndex()+1);} 
        catch (SQLException ex) {Logger.getLogger(AgregarFrm.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_cajaFaseItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String codPyto=T1.getText();
        String codSNIP=T2.getText();
        String nombPyto=T3.getText();
        java.sql.Date fecReg=new java.sql.Date(dateBox1.getSelectedDate().getTimeInMillis());
        String costoPIP=T4.getText().replaceAll(",", "");
        String costoDIR=T5.getText().replaceAll(",", "");
        
       
        int codFuncion=cajaFuncion.getSelectedIndex()+1;                               //No puede ser Nulo
        int codEstado=cajaEstado.getSelectedIndex()+1;                                //No puede ser Nulo
        int codFase=cajaFase.getSelectedIndex()+1;
         int codNivel=cajaNivel.getSelectedIndex()+1;                                 //No puede ser Nulo
        codNivel=procesarFase(codNivel,codFase);                                //Obtiene el nivel respectivo
        
        
        //System.out.println("Cod. de Nivel, Funcion, Estado y Fase: "+codNivel+codFuncion+codEstado+codFase);
        String codDpto=ObtenerEntero3Cifras(jCBDepartamento.getSelectedIndex()+1);
        String codProv=ObtenerEntero3Cifras(jCBProvincia.getSelectedIndex()+1);
        String codDist=ObtenerEntero3Cifras(jCBDistrito.getSelectedIndex()+1);
        String nombCliente=String.valueOf(cajaCliente.getSelectedItem());   //No puede ser Nulo
        String nombEsp=String.valueOf(cajaEspecialista.getSelectedItem());       //No puede ser Nulo
        String nombResp=String.valueOf(cajaResponsable.getSelectedItem());       //No puede ser Nulo
        String Observac=jTextArea1.getText().replaceAll("\n", " ");
        Observac= (Observac.equals(""))?" ":Observac;
        String Vigente=(jCheckBox1.isSelected())?"1":"0";
        
        if(!nombPyto.equals("") && !costoPIP.equals("") && !costoDIR.equals("") && !codDpto.equals("000") && !codProv.equals("000") && !codDist.equals("000"))
            if(comprobarDouble(costoPIP) || comprobarDouble(costoDIR)){
            try {
                Logica.actualizarProyecto(codPyto,codFase,codNivel,codSNIP, nombPyto, fecReg, Double.parseDouble(costoPIP), Double.parseDouble(costoDIR), codEstado, ObtenerEntero4Cifras(codFuncion), codDpto, codProv, codDist, nombCliente, nombEsp, nombResp,Observac, Vigente);
                System.out.println("Flag n");
                Logica.Commit();
                this.dispose();
                //new BuscarFrm('m').setVisible(true);
            } 
                catch (SQLException ex) {Logger.getLogger(ModificarFrm.class.getName()).log(Level.SEVERE, null, ex);}
                
            }
            else
                JOptionPane.showMessageDialog(this, "Los Costos de PIP y DIR no son adecuados");
        else
            JOptionPane.showMessageDialog(this, "Le falta llenar algun campo.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FormatoNumero(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FormatoNumero
        char entrada=evt.getKeyChar();
        
        javax.swing.JTextField aux=(javax.swing.JTextField)evt.getComponent();
        
        if(Character.isDigit(entrada) || entrada=='.'){
            String txt=aux.getText();
            if(entrada!='.'){
                txt=txt.replaceAll(",", "");
                double valor=Double.parseDouble(txt);
                aux.setText(formateador.format(valor));
            } 
        }
        else{
            evt.consume();
        }
    }//GEN-LAST:event_FormatoNumero

    private void IngresarNumero(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarNumero
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.')
            evt.consume();
    }//GEN-LAST:event_IngresarNumero

    
    //Funciones de Comprobación
    private boolean comprobarDouble(String numero){
        try{
            Double.parseDouble(numero);
            return true;
        }catch(Exception e){
            return false;
        }
    }
    private String ObtenerEntero3Cifras(int numero){
        int tam= Integer.toString(numero).length();
        switch (tam){
            case 1: return "00"+Integer.toString(numero);
            case 2: return "0"+Integer.toString(numero);
            case 3: return Integer.toString(numero);
        }
        return null;
    }
    private String ObtenerEntero4Cifras(int numero){
        int tam= Integer.toString(numero).length();
        switch (tam){
            case 1: return "000"+Integer.toString(numero);
            case 2: return "00"+Integer.toString(numero);
            case 3: return "0"+Integer.toString(numero);
            case 4: return Integer.toString(numero);
        }
        return null;
    }
    private int procesarFase(int codnivel,int codfase){
        switch(codfase){
            case 1:             //Fase preinversion tiene niveles 1 y 2
                return codnivel;
            case 2:
                return codnivel+2;    //Fase inversion tiene niveles 3 y 4
            case 3:
                return codnivel+4;    //Fase posinversion tiene niveles 5 y 6
            default:
                return -1;
        }
    }
    
    //Funciones para agregar datos
    private void agregarNiveles(int codfase) throws SQLException{
        cajaNivel.removeAllItems();
        String[] Nivel=Logica.leerNiveles(codfase).split("#"); //Deben existir al menos 1 nivel
        int tam=Nivel.length;
        
        for(int i=0;i<tam;i++)
            cajaNivel.addItem(Nivel[i]);
    }
    private void agregarFunciones() throws SQLException{
        String[] Funcion=Logica.leerFunciones().split("#"); //Deben existir al menos 1 funcion
        int tam=Funcion.length;
        for(int i=0;i<tam;i++)
            cajaFuncion.addItem(Funcion[i]);
    }
    private void agregarEstados(JComboBox caja) throws SQLException{
        String[] Estado=Logica.leerEstados().split("#"); //Deben existir al menos 1 estado
        int tam=Estado.length;
        for(int i=0;i<tam;i++)
            caja.addItem(Estado[i]);
    }
    private void agregarFases() throws SQLException{
        String[] Estado=Logica.leerFases().split("#"); //Deben existir al menos 1 estado
        int tam=Estado.length;
        for(int i=0;i<tam;i++)
            cajaFase.addItem(Estado[i]);
    }
    private void agregarDepartamentos() throws SQLException{
        String[] Departamento=Logica.leerDepartamentos().split("#"); //Deben existir al menos 1 departamento
        int tam=Departamento.length;
        for(int i=0;i<tam;i++)
            jCBDepartamento.addItem(Departamento[i]);
        jCBDepartamento.setSelectedIndex(-1);
    }
    private void agregarProvincias() throws SQLException{
        String[] Provincia=Logica.leerProvincias(String.valueOf(jCBDepartamento.getSelectedItem())).split("#"); //Deben existir al menos 1 provincia
        int tam=Provincia.length;
        jCBProvincia.removeAllItems();
        for(int i=0;i<tam;i++)
            jCBProvincia.addItem(Provincia[i]);
    }
    private void agregarDistritos() throws SQLException{
        String[] Distrito=Logica.leerDistritos(String.valueOf(jCBProvincia.getSelectedItem()),String.valueOf(jCBDepartamento.getSelectedItem())).split("#"); //Deben existir al menos 1 distrito
        int tam=Distrito.length;
        jCBDistrito.removeAllItems();
        for(int i=0;i<tam;i++)
            jCBDistrito.addItem(Distrito[i]);
    }
    private void agregarClientes() throws SQLException{
        String[] Cliente=Logica.leerClientes().split("#"); //Deben existir al menos 1 nivel
        int tam=Cliente.length;
        for(int i=0;i<tam;i++)
            cajaCliente.addItem(Cliente[i]);
    }
    private void agregarEspecialistas() throws SQLException{
        String[] Especialista=Logica.leerEspecialistas().split("#"); //Deben existir al menos 1 nivel
        int tam=Especialista.length;
        for(int i=0;i<tam;i++)
            cajaEspecialista.addItem(Especialista[i]);
    }
    private void agregarResponsable() throws SQLException{
        String[] Responsable=Logica.leerEspecialistas().split("#"); //Deben existir al menos 1 nivel
        int tam=Responsable.length;
        for(int i=0;i<tam;i++)
            cajaResponsable.addItem(Responsable[i]);
    }

    
    //Funcion de Recuperacion de la Base de Datos
    private void recuperarDatos() throws SQLException{
        Object[] datos=Logica.recuperarProyecto(codPyto);
        T1.setText(String.valueOf(datos[0]));   //CodPyto
        cajaFase.setSelectedItem(String.valueOf(datos[1]));   //nombFase
        agregarNiveles(cajaFase.getSelectedIndex()+1);
        cajaNivel.setSelectedItem(String.valueOf(datos[2]));    //nombNivel
        T2.setText(String.valueOf(datos[3])); //codSNIP
        T3.setText(String.valueOf(datos[4]));   //NomPyto
        Calendar Cal = new GregorianCalendar();Cal.setTimeInMillis(Long.parseLong(String.valueOf(datos[5])));
        dateBox1.setCurrent(Cal);           //FecReg
        dateBox1.setText(Cal.get(Calendar.DAY_OF_MONTH)+"/"+(Cal.get(Calendar.MONTH)+1)+"/"+Cal.get(Calendar.YEAR));
        dateBox1.setEnabled(false);
        
        T4.setText(formateador.format(Double.parseDouble(String.valueOf(datos[6]))));   //Costo PIP
        T5.setText(formateador.format(Double.parseDouble(String.valueOf(datos[7]))));   //Costo DIR
        cajaEstado.setSelectedItem((String.valueOf(datos[8])));    //EstPyto
        cajaFuncion.setSelectedItem((String.valueOf(datos[9])));    //CodFuncion
        jCBDepartamento.setSelectedItem((String.valueOf(datos[10])));    //codDepartamento
        jCBProvincia.setSelectedItem((String.valueOf(datos[11])));    //codProvincia
        jCBDistrito.setSelectedItem((String.valueOf(datos[12])));     //codDistrito
        cajaCliente.setSelectedItem(datos[13]);            //codCliente
        cajaEspecialista.setSelectedItem(datos[14]);            //codEspecialista
        cajaResponsable.setSelectedItem(datos[15]);           //codResponsable
        jTextArea1.setText(datos[16].toString());   //Observación
        jCheckBox1.setSelected((datos[17]).equals("1")?true:false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JComboBox<String> cajaCliente;
    private javax.swing.JComboBox<String> cajaEspecialista;
    private javax.swing.JComboBox<String> cajaEstado;
    private javax.swing.JComboBox<String> cajaFase;
    private javax.swing.JComboBox<String> cajaFuncion;
    private javax.swing.JComboBox<String> cajaNivel;
    private javax.swing.JComboBox<String> cajaResponsable;
    private datechooser.beans.DateChooserCombo dateBox1;
    private javax.swing.JButton jButton2;
    private org.edisoncor.gui.button.ButtonTask jButton3;
    private javax.swing.JComboBox<String> jCBDepartamento;
    private javax.swing.JComboBox<String> jCBDistrito;
    private javax.swing.JComboBox<String> jCBProvincia;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.label.LabelTask labelTask2;
    private org.edisoncor.gui.label.LabelTask labelTask3;
    // End of variables declaration//GEN-END:variables
}
