/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Principal;

import edu.unmsm.sistemas.sgpy.ProfYExp.Conexion.Conexion;
import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Empresa.FrameListarEmpresas;
import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Empresa.I_CumpleaniosGerente;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Casa
 */
public class I_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form I_MenuPrincipal
     */
    public I_MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("COSAPI");
        this.setSize(738,520);
        //System.out.println(insertarFoto("101010")); 
    }
    
    public boolean insertarFoto(String cod) {
        boolean insertado = false;
        try {
            String sql = "INSERT INTO PERSONA (CODPERS,FOTO) VALUES (?,?)";
            PreparedStatement consulta = Conexion.getConnection().prepareStatement(sql);
            File imagen = new File("101010.jpg");
            FileInputStream fis = new FileInputStream(imagen);
            consulta.setInt(1, Integer.parseInt(cod));
            consulta.setBinaryStream(2, fis);
            
            int r = consulta.executeUpdate();
            
            
            if(r==1)
                insertado=true;
        } catch (SQLException ex) {
            Logger.getLogger(I_MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(I_MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return insertado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuProfesional = new javax.swing.JMenuItem();
        jMenuProfesion = new javax.swing.JMenuItem();
        jMenuCostos = new javax.swing.JMenuItem();
        jMenuEmpresa = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jMenuProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoProfesion.png"))); // NOI18N
        jMenuProfesional.setText("Profesional");
        jMenuProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProfesionalActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuProfesional);

        jMenuProfesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoProfesion1.png"))); // NOI18N
        jMenuProfesion.setText("Profesion");
        jMenuProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProfesionActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuProfesion);

        jMenuCostos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoCostos.png"))); // NOI18N
        jMenuCostos.setText("Costos Proyectos");
        jMenuCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCostosActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuCostos);

        jMenuEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoEmpresa.png"))); // NOI18N
        jMenuEmpresa.setText("Empresa");
        jMenuEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmpresaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuEmpresa);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setComponentPopupMenu(jPopupMenu1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/cosapi.png"))); // NOI18N
        jLabel1.setOpaque(true);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/COSAPIPROYECTO2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COSAPI, con más de 50 años en el mercado, es la segunda empresa ");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("  de ingeniería y construcción de capital nacional en el Perú. ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfesionalActionPerformed
        new I_MenuProfesional().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuProfesionalActionPerformed

    private void jMenuProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfesionActionPerformed
        new I_MenuProfesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuProfesionActionPerformed

    private void jMenuCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCostosActionPerformed
       new I_MenuCostos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuCostosActionPerformed

    private void jMenuEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmpresaActionPerformed
        try {
            new I_CumpleaniosGerente().setVisible(true);    
        } catch (SQLException | IOException ex) {
            Logger.getLogger(I_MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        new FrameListarEmpresas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuCostos;
    private javax.swing.JMenuItem jMenuEmpresa;
    private javax.swing.JMenuItem jMenuProfesion;
    private javax.swing.JMenuItem jMenuProfesional;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
