/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Profesional;


import edu.unmsm.sistemas.sgpy.ProfYExp.Conexion.Conexion;
import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Principal.I_MenuProfesional;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleCallableStatement;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Joselyn CCanto
 */
public class I_BusquedaProfesion extends javax.swing.JFrame {

    
    DefaultTableModel modeloTabla;
    int banderaProf,banderaUni,banderaCargo,banderaExp;
    boolean op;
    
    public I_BusquedaProfesion() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
        labelProf.setVisible(false);
        labelUni.setVisible(false);
        labelCargo.setVisible(false);
        labelAnios.setVisible(false);
        txtProf.setVisible(false);
        txtUni.setVisible(false);
        txtCargo.setVisible(false);
        txtExp.setVisible(false);
        banderaProf=0;
        banderaUni=0;
        banderaCargo=0;
        banderaExp=0;
        op=true;
        /***************************************/
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Codigo Persona");
        modeloTabla.addColumn("Des. Persona");
        modeloTabla.addColumn("Des. Corta");
        modeloTabla.addColumn("Cargo");
        modeloTabla.addColumn("Grado");
        modeloTabla.addColumn("Des. Prof");
        modeloTabla.addColumn("Nro. CIP");
        modeloTabla.addColumn("Vigente");
        modeloTabla.addColumn("Universidad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaDespelgable = new javax.swing.JPopupMenu();
        RegistrarProfesional = new javax.swing.JMenuItem();
        ModificarProfesional = new javax.swing.JMenuItem();
        EliminarProfesional = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        botonPrincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelAnios = new javax.swing.JLabel();
        txtProf = new javax.swing.JTextField();
        checkProf = new javax.swing.JCheckBox();
        checkUni = new javax.swing.JCheckBox();
        checkCargo = new javax.swing.JCheckBox();
        checkAnios = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelProf = new javax.swing.JLabel();
        labelUni = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        txtUni = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtExp = new javax.swing.JTextField();
        btnSalirM = new javax.swing.JButton();

        ListaDespelgable.setComponentPopupMenu(ListaDespelgable);

        RegistrarProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoAgregarProfesional.png"))); // NOI18N
        RegistrarProfesional.setText("Registrar Profesional");
        RegistrarProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProfesionalActionPerformed(evt);
            }
        });
        ListaDespelgable.add(RegistrarProfesional);

        ModificarProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoModificarProfesional.png"))); // NOI18N
        ModificarProfesional.setText("Modificar Profesional");
        ModificarProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProfesionalActionPerformed(evt);
            }
        });
        ListaDespelgable.add(ModificarProfesional);

        EliminarProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoEliminarProfesional.png"))); // NOI18N
        EliminarProfesional.setText("Eliminar Profesional");
        EliminarProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProfesionalActionPerformed(evt);
            }
        });
        ListaDespelgable.add(EliminarProfesional);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setComponentPopupMenu(ListaDespelgable);
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.setLayout(null);

        botonPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        botonPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoBuscar.png"))); // NOI18N
        botonPrincipal.setText("BUSCAR");
        botonPrincipal.setVerifyInputWhenFocusTarget(false);
        botonPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(botonPrincipal);
        botonPrincipal.setBounds(920, 20, 170, 56);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 870, 300);

        labelAnios.setBackground(new java.awt.Color(255, 255, 255));
        labelAnios.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        labelAnios.setText("Ingrese los años de experiencia:");
        labelAnios.setOpaque(true);
        jPanel1.add(labelAnios);
        labelAnios.setBounds(520, 80, 290, 30);

        txtProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfActionPerformed(evt);
            }
        });
        jPanel1.add(txtProf);
        txtProf.setBounds(240, 30, 270, 30);

        checkProf.setText(" Profesión");
        checkProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkProfActionPerformed(evt);
            }
        });
        jPanel1.add(checkProf);
        checkProf.setBounds(930, 150, 150, 23);

        checkUni.setText("Universidad");
        checkUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUniActionPerformed(evt);
            }
        });
        jPanel1.add(checkUni);
        checkUni.setBounds(930, 180, 150, 23);

        checkCargo.setText("Cargo");
        checkCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCargoActionPerformed(evt);
            }
        });
        jPanel1.add(checkCargo);
        checkCargo.setBounds(930, 210, 150, 23);

        checkAnios.setText("Años de experiencia");
        checkAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAniosActionPerformed(evt);
            }
        });
        jPanel1.add(checkAnios);
        checkAnios.setBounds(930, 240, 150, 23);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("  Buscar por:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(930, 110, 140, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(910, 90, 190, 190);

        labelProf.setBackground(new java.awt.Color(255, 255, 255));
        labelProf.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        labelProf.setText("Ingrese la Profesión:");
        labelProf.setOpaque(true);
        jPanel1.add(labelProf);
        labelProf.setBounds(20, 30, 200, 30);

        labelUni.setBackground(new java.awt.Color(255, 255, 255));
        labelUni.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        labelUni.setText("Ingrese la Universidad:");
        labelUni.setOpaque(true);
        jPanel1.add(labelUni);
        labelUni.setBounds(20, 80, 220, 30);

        labelCargo.setBackground(new java.awt.Color(255, 255, 255));
        labelCargo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        labelCargo.setText("Ingrese el cargo: ");
        labelCargo.setOpaque(true);
        jPanel1.add(labelCargo);
        labelCargo.setBounds(520, 30, 200, 30);

        txtUni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtUni);
        txtUni.setBounds(250, 80, 260, 30);

        txtCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtCargo);
        txtCargo.setBounds(730, 30, 160, 30);

        txtExp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtExp);
        txtExp.setBounds(820, 80, 70, 30);

        btnSalirM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoSalir.png"))); // NOI18N
        btnSalirM.setText("SALIR");
        btnSalirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalirM);
        btnSalirM.setBounds(941, 410, 120, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void checkAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAniosActionPerformed
        txtExp.setText("");
        if(checkAnios.isSelected()){
            labelAnios.setVisible(true);
            txtExp.setVisible(true);
            banderaExp=1;
        }else{
            labelAnios.setVisible(false);
            txtExp.setVisible(false);
            banderaExp=0;
        }
    }//GEN-LAST:event_checkAniosActionPerformed

    private void checkCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCargoActionPerformed
        txtCargo.setText("");
        if(checkCargo.isSelected()){
            labelCargo.setVisible(true);
            txtCargo.setVisible(true);
            banderaCargo=1;
        }else{
            labelCargo.setVisible(false);
            txtCargo.setVisible(false);
            banderaCargo=0;
        }
    }//GEN-LAST:event_checkCargoActionPerformed

    private void checkUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUniActionPerformed
        txtUni.setText("");
        if(checkUni.isSelected()){
            labelUni.setVisible(true);
            txtUni.setVisible(true);
            banderaUni=1;
        }
        else{
            labelUni.setVisible(false);
            txtUni.setVisible(false);
            banderaUni=0;
        }
    }//GEN-LAST:event_checkUniActionPerformed

    private void checkProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkProfActionPerformed
        txtProf.setText("");
        if(checkProf.isSelected()){
            labelProf.setVisible(true);
            txtProf.setVisible(true);
            banderaProf=1;
        }else{
            labelProf.setVisible(false);
            txtProf.setVisible(false);
            banderaProf=0;
        }
    }//GEN-LAST:event_checkProfActionPerformed

    private void txtProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfActionPerformed

    public void Profesion(DefaultTableModel modeloTabla){
        
    }
    private void botonPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrincipalActionPerformed
        String profesion, universidad, cargo;
        int experiencia;
        
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Codigo Persona");
        modeloTabla.addColumn("Des. Persona");
        modeloTabla.addColumn("Des. Corta");
        modeloTabla.addColumn("Cargo");
        modeloTabla.addColumn("Grado");
        modeloTabla.addColumn("Des. Prof");
        modeloTabla.addColumn("Nro. CIP");
        modeloTabla.addColumn("Vigente");
        modeloTabla.addColumn("Universidad");
        /**CON UNO**/
        if(banderaProf==1 && banderaUni==0 && banderaCargo==0 && banderaExp==0){
            Object obj[] =new Object[9] ;
            JTable tabla_buscar;
            profesion=txtProf.getText();
            Connection connection;
            //jScrollPane1.removeAll();
            try {
                connection=Conexion.getConnection();
                System.out.println("entre a prof");
                try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_prof (?,?)}")){
                    consulta.setString(1, profesion);
                    consulta.registerOutParameter(2, OracleTypes.CURSOR);
                    consulta.execute();

                    try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(2)){

                        while(rs.next()){
                            obj[0]=rs.getString(1);
                            obj[1]=rs.getString(2);
                            obj[2]=rs.getString(3);
                            //obj[3]=rs.getString(4);
                            obj[3]=rs.getString(5);
                            obj[4]=rs.getString(6);
                            obj[5]=rs.getString(7);
                            obj[6]=rs.getString(8);
                            obj[7]=rs.getString(9);
                            obj[8]=rs.getString(10);
                            modeloTabla.addRow(obj);
                        }
                        tabla_buscar = new JTable();
                        tabla_buscar.setModel(modeloTabla);
                        jScrollPane1.setViewportView(tabla_buscar);

                    }

                }

            } catch (SQLException ex) {
                Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            if(banderaProf==0 && banderaUni==1 && banderaCargo==0 && banderaExp==0){
                Object obj[] =new Object[9] ;
                JTable tabla_buscar;
                universidad=txtUni.getText();
                Connection connection;
                //jScrollPane1.removeAll();
                try {
                    connection=Conexion.getConnection();
                    System.out.println("entre a univ");
                    try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_univ (?,?)}")){
                        consulta.setString(1, universidad);
                        consulta.registerOutParameter(2, OracleTypes.CURSOR);
                        consulta.execute();

                        try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(2)){

                            while(rs.next()){
                                obj[0]=rs.getString(1);
                                obj[1]=rs.getString(2);
                                obj[2]=rs.getString(3);
                                //obj[3]=rs.getString(4);
                                obj[3]=rs.getString(5);
                                obj[4]=rs.getString(6);
                                obj[5]=rs.getString(7);
                                obj[6]=rs.getString(8);
                                obj[7]=rs.getString(9);
                                obj[8]=rs.getString(10);
                                modeloTabla.addRow(obj);
                            }
                            tabla_buscar = new JTable();
                            tabla_buscar.setModel(modeloTabla);
                            jScrollPane1.setViewportView(tabla_buscar);

                        }

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                if(banderaProf==0 && banderaUni==0 && banderaCargo==1 && banderaExp==0){
                    Object obj[] =new Object[9] ;
                    JTable tabla_buscar;
                    cargo=txtCargo.getText();
                    Connection connection;
                    
                    try {
                        connection=Conexion.getConnection();
                        System.out.println("entre a cargo");
                        try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_cargo (?,?)}")){
                            consulta.setString(1, cargo);
                            consulta.registerOutParameter(2, OracleTypes.CURSOR);
                            consulta.execute();

                            try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(2)){

                                while(rs.next()){
                                    obj[0]=rs.getString(1);
                                    obj[1]=rs.getString(2);
                                    obj[2]=rs.getString(3);
                                    //obj[3]=rs.getString(4);
                                    obj[3]=rs.getString(5);
                                    obj[4]=rs.getString(6);
                                    obj[5]=rs.getString(7);
                                    obj[6]=rs.getString(8);
                                    obj[7]=rs.getString(9);
                                    obj[8]=rs.getString(10);
                                    modeloTabla.addRow(obj);
                                }
                                tabla_buscar = new JTable();
                                tabla_buscar.setModel(modeloTabla);
                                jScrollPane1.setViewportView(tabla_buscar);

                            }

                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    if(banderaProf==0 && banderaUni==0 && banderaCargo==0 && banderaExp==1){
                        Object obj[] =new Object[9] ;
                        JTable tabla_buscar;
                        experiencia=Integer.parseInt(txtExp.getText());
                        Connection connection;
                        
                        try {
                            connection=Conexion.getConnection();
                            try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_exp_solo(?,?)}")){
                                System.out.println("Entre exp solo");
                                System.out.println(experiencia);
                                consulta.setInt(1, experiencia);
                                consulta.registerOutParameter(2, OracleTypes.CURSOR);
                                consulta.execute();

                                try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(2)){
                                    
                                    while(rs.next()){
                                        
                                        obj[0]=rs.getString(1);
                                        obj[1]=rs.getString(2);
                                        obj[2]=rs.getString(3);
                                        //obj[3]=rs.getString(4);
                                        obj[3]=rs.getString(5);
                                        obj[4]=rs.getString(6);
                                        obj[5]=rs.getString(7);
                                        obj[6]=rs.getString(8);
                                        obj[7]=rs.getString(9);
                                        obj[8]=rs.getString(10);
                                        modeloTabla.addRow(obj);
                                    }
                                    tabla_buscar = new JTable();
                                    tabla_buscar.setModel(modeloTabla);
                                    jScrollPane1.setViewportView(tabla_buscar);

                                }

                            }

                        } catch (SQLException ex) {
                            Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
            }
        }
        /**CON DOS**/
        if(banderaProf==1 && banderaUni==1 && banderaCargo==0 && banderaExp==0){
            Object obj[] =new Object[9] ;
            JTable tabla_buscar;
            profesion=txtProf.getText();
            universidad=txtUni.getText();
            Connection connection;
            
            try {
                connection=Conexion.getConnection();
                System.out.println("entre a prof+uni");
                try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_prof_uni (?,?,?)}")){
                consulta.setString(1, profesion);
                consulta.setString(2, universidad);
                consulta.registerOutParameter(3, OracleTypes.CURSOR);
                consulta.execute();
                    try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(3)){
                        while(rs.next()){
                            obj[0]=rs.getString(1);
                            obj[1]=rs.getString(2);
                            obj[2]=rs.getString(3);
                          //obj[3]=rs.getString(4);
                            obj[3]=rs.getString(5);
                            obj[4]=rs.getString(6);
                            obj[5]=rs.getString(7);
                            obj[6]=rs.getString(8);
                            obj[7]=rs.getString(9);
                            obj[8]=rs.getString(10);
                            modeloTabla.addRow(obj);
                        }
                        tabla_buscar = new JTable();
                        tabla_buscar.setModel(modeloTabla);
                        jScrollPane1.setViewportView(tabla_buscar);

                    }

                }

            } catch (SQLException ex) {
                            Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
            }      
        }else{
            if(banderaProf==1 && banderaUni==0 && banderaCargo==1 && banderaExp==0){
                Object obj[] =new Object[9] ;
                JTable tabla_buscar;
                profesion=txtProf.getText();
                cargo=txtCargo.getText();
                Connection connection;
                
                try {
                    connection=Conexion.getConnection();
                    try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_prof_cargo (?,?,?)}")){
                    consulta.setString(1, profesion);
                    consulta.setString(2, cargo);
                    consulta.registerOutParameter(3, OracleTypes.CURSOR);
                    consulta.execute();
                        try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(3)){
                            while(rs.next()){
                                obj[0]=rs.getString(1);
                                obj[1]=rs.getString(2);
                                obj[2]=rs.getString(3);
                              //obj[3]=rs.getString(4);
                                obj[3]=rs.getString(5);
                                obj[4]=rs.getString(6);
                                obj[5]=rs.getString(7);
                                obj[6]=rs.getString(8);
                                obj[7]=rs.getString(9);
                                obj[8]=rs.getString(10);
                                modeloTabla.addRow(obj);
                            }
                            tabla_buscar = new JTable();
                            tabla_buscar.setModel(modeloTabla);
                            jScrollPane1.setViewportView(tabla_buscar);

                        }

                    }

                } catch (SQLException ex) {
                                Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                }      
            }else{
                if(banderaProf==1 && banderaUni==0 && banderaCargo==0 && banderaExp==1){
                    Object obj[] =new Object[9] ;
                    JTable tabla_buscar;
                    profesion=txtProf.getText();
                    experiencia=Integer.parseInt(txtExp.getText());
                    Connection connection;
                    
                    try {
                        connection=Conexion.getConnection();
                        try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_prof_exp(?,?,?)}")){
                            System.out.println("Comence a entrar");
                        consulta.setString(1, profesion);
                        consulta.setInt(2, experiencia);
                        consulta.registerOutParameter(3, OracleTypes.CURSOR);
                        consulta.execute();
                            try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(3)){
                                while(rs.next()){
                                    obj[0]=rs.getString(1);
                                    obj[1]=rs.getString(2);
                                    obj[2]=rs.getString(3);
                                  //obj[3]=rs.getString(4);
                                    obj[3]=rs.getString(5);
                                    obj[4]=rs.getString(6);
                                    obj[5]=rs.getString(7);
                                    obj[6]=rs.getString(8);
                                    obj[7]=rs.getString(9);
                                    obj[8]=rs.getString(10);
                                    modeloTabla.addRow(obj);
                                }
                                tabla_buscar = new JTable();
                                tabla_buscar.setModel(modeloTabla);
                                jScrollPane1.setViewportView(tabla_buscar);

                            }

                        }

                    } catch (SQLException ex) {
                                    Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                    }      
                }else{
                    if(banderaProf==0 && banderaUni==1 && banderaCargo==1 && banderaExp==0){
                        Object obj[] =new Object[9] ;
                        JTable tabla_buscar;
                        universidad=txtUni.getText();
                        cargo=txtCargo.getText();
                        Connection connection;
                        
                        try {
                            connection=Conexion.getConnection();
                            try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_uni_cargo (?,?,?)}")){
                            consulta.setString(1, universidad);
                            consulta.setString(2, cargo);
                            consulta.registerOutParameter(3, OracleTypes.CURSOR);
                            consulta.execute();
                                try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(3)){
                                    while(rs.next()){
                                        obj[0]=rs.getString(1);
                                        obj[1]=rs.getString(2);
                                        obj[2]=rs.getString(3);
                                      //obj[3]=rs.getString(4);
                                        obj[3]=rs.getString(5);
                                        obj[4]=rs.getString(6);
                                        obj[5]=rs.getString(7);
                                        obj[6]=rs.getString(8);
                                        obj[7]=rs.getString(9);
                                        obj[8]=rs.getString(10);
                                        modeloTabla.addRow(obj);
                                    }
                                    tabla_buscar = new JTable();
                                    tabla_buscar.setModel(modeloTabla);
                                    jScrollPane1.setViewportView(tabla_buscar);

                                }

                            }

                        } catch (SQLException ex) {
                                        Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                        }   
                    }
                    else{
                        if(banderaProf==0 && banderaUni==1 && banderaCargo==0 && banderaExp==1){
                            Object obj[] =new Object[9] ;
                            JTable tabla_buscar;
                            universidad=txtUni.getText();
                            experiencia=Integer.parseInt(txtExp.getText());
                            Connection connection;
                            
                            try {
                                connection=Conexion.getConnection();
                                try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_uni_exp(?,?,?)}")){
                                consulta.setString(1, universidad);
                                consulta.setInt(2, experiencia);
                                consulta.registerOutParameter(3, OracleTypes.CURSOR);
                                consulta.execute();
                                    try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(3)){
                                        while(rs.next()){
                                            obj[0]=rs.getString(1);
                                            obj[1]=rs.getString(2);
                                            obj[2]=rs.getString(3);
                                          //obj[3]=rs.getString(4);
                                            obj[3]=rs.getString(5);
                                            obj[4]=rs.getString(6);
                                            obj[5]=rs.getString(7);
                                            obj[6]=rs.getString(8);
                                            obj[7]=rs.getString(9);
                                            obj[8]=rs.getString(10);
                                            modeloTabla.addRow(obj);
                                        }
                                        tabla_buscar = new JTable();
                                        tabla_buscar.setModel(modeloTabla);
                                        jScrollPane1.setViewportView(tabla_buscar);

                                    }

                                }

                            } catch (SQLException ex) {
                                            Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                            }   
                        }
                        else{
                            if(banderaProf==0 && banderaUni==0 && banderaCargo==1 && banderaExp==1){
                                Object obj[] =new Object[9] ;
                                JTable tabla_buscar;
                                cargo=txtCargo.getText();
                                experiencia=Integer.parseInt(txtExp.getText());
                                Connection connection;
                                
                                try {
                                    connection=Conexion.getConnection();
                                    try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_exper (?,?,?)}")){
                                        consulta.setString(1, cargo);
                                        consulta.setInt(2, experiencia);
                                        consulta.registerOutParameter(3, OracleTypes.CURSOR);
                                        consulta.execute();

                                        try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(3)){

                                            while(rs.next()){
                                                obj[0]=rs.getString(1);
                                                obj[1]=rs.getString(2);
                                                obj[2]=rs.getString(3);
                                                //obj[3]=rs.getString(4);
                                                obj[3]=rs.getString(5);
                                                obj[4]=rs.getString(6);
                                                obj[5]=rs.getString(7);
                                                obj[6]=rs.getString(8);
                                                obj[7]=rs.getString(9);
                                                obj[8]=rs.getString(10);
                                                modeloTabla.addRow(obj);
                                            }
                                            tabla_buscar = new JTable();
                                            tabla_buscar.setModel(modeloTabla);
                                            jScrollPane1.setViewportView(tabla_buscar);

                                        }

                                    }

                                } catch (SQLException ex) {
                                    Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }
                    }
                }
            }
        }
        /**CON TRES**/
        if(banderaProf==1 && banderaUni==1 && banderaCargo==1 && banderaExp==0){
            Object obj[] =new Object[9] ;
            JTable tabla_buscar;
            profesion=txtProf.getText();
            universidad=txtUni.getText();
            cargo=txtCargo.getText();
            Connection connection;
            
            try {
                connection=Conexion.getConnection();
                try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_prof_uni_cargo (?,?,?,?)}")){
                consulta.setString(1, profesion);
                consulta.setString(2, universidad);
                consulta.setString(3, cargo);
                consulta.registerOutParameter(4, OracleTypes.CURSOR);
                consulta.execute();
                    try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(4)){
                        while(rs.next()){
                            obj[0]=rs.getString(1);
                            obj[1]=rs.getString(2);
                            obj[2]=rs.getString(3);
                          //obj[3]=rs.getString(4);
                            obj[3]=rs.getString(5);
                            obj[4]=rs.getString(6);
                            obj[5]=rs.getString(7);
                            obj[6]=rs.getString(8);
                            obj[7]=rs.getString(9);
                            obj[8]=rs.getString(10);
                            modeloTabla.addRow(obj);
                        }
                        tabla_buscar = new JTable();
                        tabla_buscar.setModel(modeloTabla);
                        jScrollPane1.setViewportView(tabla_buscar);

                    }

                }

            } catch (SQLException ex) {
                            Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }else{
            if(banderaProf==1 && banderaUni==0 && banderaCargo==1 && banderaExp==1){
                Object obj[] =new Object[9] ;
                JTable tabla_buscar;
                profesion=txtProf.getText();
                cargo=txtCargo.getText();
                experiencia=Integer.parseInt(txtExp.getText());
                Connection connection;
               
                try {
                    connection=Conexion.getConnection();
                    try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_prof_cargo_exp(?,?,?,?)}")){
                    consulta.setString(1, profesion);
                    consulta.setString(2, cargo);
                    consulta.setInt(3, experiencia);
                    consulta.registerOutParameter(4, OracleTypes.CURSOR);
                    consulta.execute();
                        try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(4)){
                            while(rs.next()){
                                obj[0]=rs.getString(1);
                                obj[1]=rs.getString(2);
                                obj[2]=rs.getString(3);
                              //obj[3]=rs.getString(4);
                                obj[3]=rs.getString(5);
                                obj[4]=rs.getString(6);
                                obj[5]=rs.getString(7);
                                obj[6]=rs.getString(8);
                                obj[7]=rs.getString(9);
                                obj[8]=rs.getString(10);
                                modeloTabla.addRow(obj);
                            }
                            tabla_buscar = new JTable();
                            tabla_buscar.setModel(modeloTabla);
                            jScrollPane1.setViewportView(tabla_buscar);

                        }

                    }

                } catch (SQLException ex) {
                                Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                }  
            }else{
                if(banderaProf==0 && banderaUni==1 && banderaCargo==1 && banderaExp==1){
                    Object obj[] =new Object[9] ;
                    JTable tabla_buscar;
                    universidad=txtUni.getText();
                    cargo=txtCargo.getText();
                    experiencia=Integer.parseInt(txtExp.getText());
                    Connection connection;
                   
                    try {
                        connection=Conexion.getConnection();
                        try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_uni_cargo_exp (?,?,?,?)}")){
                        consulta.setString(1, universidad);
                        consulta.setString(2, cargo);
                        consulta.setInt(3, experiencia);
                        consulta.registerOutParameter(4, OracleTypes.CURSOR);
                        consulta.execute();
                            try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(4)){
                                while(rs.next()){
                                    obj[0]=rs.getString(1);
                                    obj[1]=rs.getString(2);
                                    obj[2]=rs.getString(3);
                                  //obj[3]=rs.getString(4);
                                    obj[3]=rs.getString(5);
                                    obj[4]=rs.getString(6);
                                    obj[5]=rs.getString(7);
                                    obj[6]=rs.getString(8);
                                    obj[7]=rs.getString(9);
                                    obj[8]=rs.getString(10);
                                    modeloTabla.addRow(obj);
                                }
                                tabla_buscar = new JTable();
                                tabla_buscar.setModel(modeloTabla);
                                jScrollPane1.setViewportView(tabla_buscar);

                            }

                        }

                    } catch (SQLException ex) {
                                    Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
                    }  
                }
            }
        }
        /**CON CUATRO**/
        if(banderaProf==1 && banderaUni==1 && banderaCargo==1 && banderaExp==1){
            Object obj[] =new Object[9] ;
            JTable tabla_buscar;
            profesion=txtProf.getText();
            universidad=txtUni.getText();
            cargo=txtCargo.getText();
            experiencia=Integer.parseInt(txtExp.getText());
            Connection connection;
            
            try {
                connection=Conexion.getConnection();
                try(CallableStatement consulta = connection.prepareCall("{CALL PACKAGE_BUSQUEDA.proc_buscar_prof_uni_cargo_exp (?,?,?,?,?)}")){
                consulta.setString(1, profesion);
                consulta.setString(2, universidad);
                consulta.setString(3, cargo);
                consulta.setInt(4, experiencia);
                consulta.registerOutParameter(5, OracleTypes.CURSOR);
                consulta.execute();
                    try(ResultSet rs= ((OracleCallableStatement)consulta).getCursor(5)){
                        while(rs.next()){
                            obj[0]=rs.getString(1);
                            obj[1]=rs.getString(2);
                            obj[2]=rs.getString(3);
                          //obj[3]=rs.getString(4);
                            obj[3]=rs.getString(5);
                            obj[4]=rs.getString(6);
                            obj[5]=rs.getString(7);
                            obj[6]=rs.getString(8);
                            obj[7]=rs.getString(9);
                            obj[8]=rs.getString(10);
                            modeloTabla.addRow(obj);
                        }
                        tabla_buscar = new JTable();
                        tabla_buscar.setModel(modeloTabla);
                        jScrollPane1.setViewportView(tabla_buscar);

                    }

                }

            } catch (SQLException ex) {
                            Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }

        txtProf.setText("");
        txtUni.setText("");
        txtCargo.setText("");
        txtExp.setText("");
    }//GEN-LAST:event_botonPrincipalActionPerformed

    private void ModificarProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProfesionalActionPerformed
        I_ModificarProfesional a;
        try {
            a = new I_ModificarProfesional();
            a.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(I_RegistrarProfesional.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ModificarProfesionalActionPerformed

    private void EliminarProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProfesionalActionPerformed
        I_EliminarProfesional a = new I_EliminarProfesional();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarProfesionalActionPerformed

    private void RegistrarProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProfesionalActionPerformed
        I_RegistrarProfesional a;
        try {
            a = new I_RegistrarProfesional();
               a.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(I_BusquedaProfesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_RegistrarProfesionalActionPerformed

    private void btnSalirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMActionPerformed
        new I_MenuProfesional().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirMActionPerformed

    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_BusquedaProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_BusquedaProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_BusquedaProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_BusquedaProfesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_BusquedaProfesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EliminarProfesional;
    private javax.swing.JPopupMenu ListaDespelgable;
    private javax.swing.JMenuItem ModificarProfesional;
    private javax.swing.JMenuItem RegistrarProfesional;
    private javax.swing.JButton botonPrincipal;
    private javax.swing.JButton btnSalirM;
    private javax.swing.JCheckBox checkAnios;
    private javax.swing.JCheckBox checkCargo;
    private javax.swing.JCheckBox checkProf;
    private javax.swing.JCheckBox checkUni;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelAnios;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelProf;
    private javax.swing.JLabel labelUni;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtExp;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtUni;
    // End of variables declaration//GEN-END:variables
}
