/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Profesional;

import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Vistas_Profesional.I_EliminarProfesional;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo.Profesional;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo_DAO.PersonaDAO;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo_DAO.ProfesionDAO;
import edu.unmsm.sistemas.sgpy.ProfYExp.Modelo_DAO.ProfesionalDAO;
import edu.unmsm.sistemas.sgpy.ProfYExp.Vistas.Principal.I_MenuProfesional;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class I_ModificarProfesional extends javax.swing.JFrame {

    Profesional pr = null;
    ProfesionalDAO prf = new ProfesionalDAO();
    ResultSet rs;
    ProfesionDAO prof = new ProfesionDAO();
    PersonaDAO per = new PersonaDAO();

    public I_ModificarProfesional() throws Exception {
        initComponents();
        this.setSize(486, 550);
        this.setTitle("Modificar Profesional");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtNombrePersona.setEditable(false);
        jComboBoxEmpresa.setEditable(false);
        jComboBoxProfesion.setEditable(false);
        txtCIP.setEditable(false);
        txtUniversidad.setEditable(false);
        btnModificar.setEnabled(false);
        llenarComboProfesion();
        llenarComboEmpresa();
    }

    public void llenarComboProfesion() throws Exception {
        rs = prof.listarPorVigencia("1");
        String descripcion;
        while (rs.next()) {
            descripcion = rs.getString(3);
            jComboBoxProfesion.addItem(descripcion);
        }
    }

    public void llenarComboEmpresa() throws SQLException {
        rs = per.listarPersonaCliente();
        while (rs.next()) {
            jComboBoxEmpresa.addItem(rs.getString(1));
        }
    }

    public Profesional BuscarProfesional(String codigo) throws Exception {
        boolean bandera = false;
        Profesional pf = new Profesional();
        rs = prf.BuscarProfesional(codigo);
        while (rs.next()) {
            pf.setNomPers(rs.getString(1));
            pf.setNomEmpresa(rs.getString(2));
            pf.setDesProf(rs.getString(3));
            pf.setNroCIP(rs.getString(4));
            pf.setUniversidad(rs.getString(5));
            bandera = true;
        }

        if (!bandera) {
            return null;
        } else {
            return pf;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo_BotonesM = new javax.swing.ButtonGroup();
        ListaDespelgable = new javax.swing.JPopupMenu();
        RegistrarProfesional = new javax.swing.JMenuItem();
        EliminarProfesional = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxEmpresa = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCIP = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnCancelarM = new javax.swing.JButton();
        jComboBoxProfesion = new javax.swing.JComboBox();
        txtUniversidad = new javax.swing.JTextField();
        btnSalirM = new javax.swing.JButton();

        RegistrarProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoAgregarProfesional.png"))); // NOI18N
        RegistrarProfesional.setText("Registrar Profesional");
        RegistrarProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProfesionalActionPerformed(evt);
            }
        });
        ListaDespelgable.add(RegistrarProfesional);

        EliminarProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoEliminarProfesional.png"))); // NOI18N
        EliminarProfesional.setText("Eliminar Profesional");
        EliminarProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProfesionalActionPerformed(evt);
            }
        });
        ListaDespelgable.add(EliminarProfesional);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoBuscar.png"))); // NOI18N
        jMenuItem1.setText("Buscar Profesional");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ListaDespelgable.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Profesional", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel1.setComponentPopupMenu(ListaDespelgable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese código:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoBuscar.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Nombre:");

        txtNombrePersona.setEditable(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Nombre Empresa:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Nombre de Profesion");

        jComboBoxEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empresa" }));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("NRO CIP:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Universidad:");

        txtCIP.setEditable(false);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoModificarProfesional.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoCancelar.png"))); // NOI18N
        btnCancelarM.setText("CANCELAR");
        btnCancelarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMActionPerformed(evt);
            }
        });

        jComboBoxProfesion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Profesion" }));

        txtUniversidad.setEditable(false);

        btnSalirM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfYExp/Imagenes/iconoSalir.png"))); // NOI18N
        btnSalirM.setText("SALIR");
        btnSalirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCIP, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalirM)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBoxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBoxProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtCIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnCancelarM)
                    .addComponent(btnSalirM))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llene el codigo a Buscar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                pr = BuscarProfesional(txtBuscar.getText());
            } catch (Exception ex) {
                Logger.getLogger(I_ModificarProfesional.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtBuscar.setText("");
            if (pr != null) {

                btnModificar.setEnabled(true);
                txtNombrePersona.setEditable(true);
                jComboBoxEmpresa.setEditable(true);
                jComboBoxProfesion.setEditable(true);
                txtCIP.setEditable(true);
                txtUniversidad.setEditable(true);
                txtNombrePersona.setText(pr.getNomPers());
                jComboBoxEmpresa.setSelectedItem(pr.getNomEmpresa());
                jComboBoxProfesion.setSelectedItem(pr.getDesProf());
                txtCIP.setText(pr.getNroCIP());
                txtUniversidad.setText(pr.getUniversidad());

            } else {
                JOptionPane.showMessageDialog(rootPane, "PERSONA NO ENCONTRADA", "NOTIFICACIÓN", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtCIP.getText().equals("")) {
            txtCIP.setBackground(Color.red);
        } else {
            txtCIP.setBackground(Color.WHITE);
        }

        if (txtUniversidad.getText().equals("")) {
            txtUniversidad.setBackground(Color.red);
        } else {
            txtUniversidad.setBackground(Color.WHITE);
        }

        if ((jComboBoxProfesion.getSelectedIndex() == 0 || jComboBoxProfesion.getSelectedIndex() == -1)) {
            jComboBoxProfesion.setBackground(Color.red);
        } else {
            jComboBoxProfesion.setBackground(Color.WHITE);
        }

        if ((jComboBoxEmpresa.getSelectedIndex() == 0 || jComboBoxEmpresa.getSelectedIndex() == -1)) {
            jComboBoxEmpresa.setBackground(Color.red);
        } else {
            jComboBoxEmpresa.setBackground(Color.WHITE);
        }

        if (txtCIP.getText().equals("") || txtUniversidad.getText().equals("")
                || (jComboBoxEmpresa.getSelectedIndex() == 0 || jComboBoxEmpresa.getSelectedIndex() == -1)
                || (jComboBoxProfesion.getSelectedIndex() == 0 || jComboBoxProfesion.getSelectedIndex() == -1)) {
            JOptionPane.showMessageDialog(null, "Complete campos señalados", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            txtCIP.setBackground(Color.WHITE);
            txtUniversidad.setBackground(Color.WHITE);
            jComboBoxEmpresa.setBackground(Color.WHITE);
            jComboBoxProfesion.setBackground(Color.WHITE);
            pr.setNomPers(txtNombrePersona.getText());
            pr.setNomEmpresa(jComboBoxEmpresa.getSelectedItem().toString());
            pr.setDesProf(jComboBoxProfesion.getSelectedItem().toString());
            pr.setNroCIP(txtCIP.getText());
            pr.setUniversidad(txtUniversidad.getText());
            pr.setVigente("1");
            prf.Modificar(pr);
            JOptionPane.showMessageDialog(null, "Profesional Modificado", "Registrar", JOptionPane.INFORMATION_MESSAGE);
            txtCIP.setText("");
            txtUniversidad.setText("");
            txtNombrePersona.setText("");
            jComboBoxEmpresa.setSelectedIndex(0);
            jComboBoxProfesion.setSelectedIndex(0);
            txtNombrePersona.setEditable(false);
            jComboBoxEmpresa.setEditable(false);
            jComboBoxProfesion.setEditable(false);
            txtCIP.setEditable(false);
            txtUniversidad.setEditable(false);
            btnModificar.setEnabled(false);

        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMActionPerformed
        int resultado = JOptionPane.showConfirmDialog(rootPane, "Está seguro de cancelar esta operación?", "MENSAJE DE CONFIRMACIÓN", JOptionPane.CANCEL_OPTION);
        if (resultado == 0) {
            btnModificar.setEnabled(false);
            txtCIP.setText("");
            txtUniversidad.setText("");
            txtNombrePersona.setText("");
            jComboBoxEmpresa.setSelectedIndex(0);
            jComboBoxProfesion.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnCancelarMActionPerformed

    private void RegistrarProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProfesionalActionPerformed
        I_RegistrarProfesional a;
        try {
            a = new I_RegistrarProfesional();
            a.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(I_ModificarProfesional.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_RegistrarProfesionalActionPerformed

    private void EliminarProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProfesionalActionPerformed
        I_EliminarProfesional a = new I_EliminarProfesional();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarProfesionalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        I_BusquedaProfesion bp = new I_BusquedaProfesion();
        bp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnSalirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMActionPerformed
        new I_MenuProfesional().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_ModificarProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_ModificarProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_ModificarProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_ModificarProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new I_ModificarProfesional().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(I_ModificarProfesional.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EliminarProfesional;
    private javax.swing.ButtonGroup Grupo_BotonesM;
    private javax.swing.JPopupMenu ListaDespelgable;
    private javax.swing.JMenuItem RegistrarProfesional;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarM;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalirM;
    private javax.swing.JComboBox<String> jComboBoxEmpresa;
    private javax.swing.JComboBox jComboBoxProfesion;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCIP;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtUniversidad;
    // End of variables declaration//GEN-END:variables
}
