CREATE OR REPLACE VIEW LISTAR_PYTODOCS AS
    SELECT 
        PD.CODPYTO, 
        PD.CORRDOCS, 
        FA.DESFASE, 
        NL.DESNIVEL, 
        PD.FECINI, 
        PD.FECFIN, 
        PD.COSTOEST,
        TD.DESTDOC,
        PD.VERDOC,
        TE.DESENTREG,
        PD.VIGENTE
    FROM 
        PYTODOCS PD
    INNER JOIN NIVEL NL
    ON PD.CODNIVEL= NL.CODNIVEL
    INNER JOIN FASE FA
    ON NL.CODFASE = FA.CODFASE
    INNER JOIN TIPODOC TD
    ON PD.CODDOC = TD.CODDOC
    INNER JOIN TIPOENTREG TE
    ON PD.TIPOENTREG = TE.TIPOENTREG;

        

CREATE OR REPLACE PROCEDURE SP_LISTAR_PYTODOCS(lista_pytodocs out sys_refcursor) 
AS
BEGIN
    OPEN lista_pytodocs FOR SELECT CODPYTO FROM PYTODOCS;
END;